
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class QREPORT_COMPLETION_TIME_KPI_REF
{

    public int REF_ID { get; set; }

    public string MIN_TITLE { get; set; }

    public int MIN_SECS { get; set; }

    public string MIDDLE_TITLE { get; set; }

    public int MIDDLE_SECS { get; set; }

    public string MAX_TITLE { get; set; }

    public int MAX_SECS { get; set; }

    public string TYPE { get; set; }

}

}
