

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SAAEntities : DbContext
{
    public SAAEntities()
        : base("name=SAAEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<T_1C> T_1C { get; set; }

    public virtual DbSet<T_ACTION> T_ACTION { get; set; }

    public virtual DbSet<T_ACTION_ESCALADE> T_ACTION_ESCALADE { get; set; }

    public virtual DbSet<T_ACTION_EXPORT> T_ACTION_EXPORT { get; set; }

    public virtual DbSet<T_ACTION_EXPORT_XLS> T_ACTION_EXPORT_XLS { get; set; }

    public virtual DbSet<T_ACTION_FONCTION> T_ACTION_FONCTION { get; set; }

    public virtual DbSet<T_ACTION_FONCTION_EXTERNE> T_ACTION_FONCTION_EXTERNE { get; set; }

    public virtual DbSet<T_ACTION_IMPORT> T_ACTION_IMPORT { get; set; }

    public virtual DbSet<T_ACTION_IMPORTS_OBJ> T_ACTION_IMPORTS_OBJ { get; set; }

    public virtual DbSet<T_ACTION_MAIL> T_ACTION_MAIL { get; set; }

    public virtual DbSet<T_ACTION_POPUP> T_ACTION_POPUP { get; set; }

    public virtual DbSet<T_ACTIV> T_ACTIV { get; set; }

    public virtual DbSet<T_ACTIV_LIGNEBT> T_ACTIV_LIGNEBT { get; set; }

    public virtual DbSet<T_ADRESSE_CLIENT> T_ADRESSE_CLIENT { get; set; }

    public virtual DbSet<T_ALERTE_MV> T_ALERTE_MV { get; set; }

    public virtual DbSet<T_ALERTE_MV_ASC> T_ALERTE_MV_ASC { get; set; }

    public virtual DbSet<T_ALERTE_MV_DESC> T_ALERTE_MV_DESC { get; set; }

    public virtual DbSet<T_APPRO_STOCK> T_APPRO_STOCK { get; set; }

    public virtual DbSet<T_ARBO> T_ARBO { get; set; }

    public virtual DbSet<T_ARRET> T_ARRET { get; set; }

    public virtual DbSet<T_ARRET_BT> T_ARRET_BT { get; set; }

    public virtual DbSet<T_ARRET_IP> T_ARRET_IP { get; set; }

    public virtual DbSet<T_AVOIR> T_AVOIR { get; set; }

    public virtual DbSet<T_AVOIR_CMDE_FOURN> T_AVOIR_CMDE_FOURN { get; set; }

    public virtual DbSet<T_AVOIR_FACT_ACHAT_FOURN> T_AVOIR_FACT_ACHAT_FOURN { get; set; }

    public virtual DbSet<T_AVOIR_FACT_CLIENT> T_AVOIR_FACT_CLIENT { get; set; }

    public virtual DbSet<T_BASE> T_BASE { get; set; }

    public virtual DbSet<T_BASE_SYNCHRO_DISTANTE> T_BASE_SYNCHRO_DISTANTE { get; set; }

    public virtual DbSet<T_BL> T_BL { get; set; }

    public virtual DbSet<T_BLACKLIST_DEVICE> T_BLACKLIST_DEVICE { get; set; }

    public virtual DbSet<T_BPU> T_BPU { get; set; }

    public virtual DbSet<T_BR> T_BR { get; set; }

    public virtual DbSet<T_BR_CMDE> T_BR_CMDE { get; set; }

    public virtual DbSet<T_BS> T_BS { get; set; }

    public virtual DbSet<T_BT> T_BT { get; set; }

    public virtual DbSet<T_BT_ALERT_DEMANDEUR> T_BT_ALERT_DEMANDEUR { get; set; }

    public virtual DbSet<T_BT_GAMME2> T_BT_GAMME2 { get; set; }

    public virtual DbSet<T_BT_LIGNE_GAMME2> T_BT_LIGNE_GAMME2 { get; set; }

    public virtual DbSet<T_BT_LIGNE_GAMME2_BON_MAUVAIS> T_BT_LIGNE_GAMME2_BON_MAUVAIS { get; set; }

    public virtual DbSet<T_BT_LIGNE_GAMME2_MESURE> T_BT_LIGNE_GAMME2_MESURE { get; set; }

    public virtual DbSet<T_BT_LIGNE_GAMME2_OK_NOK> T_BT_LIGNE_GAMME2_OK_NOK { get; set; }

    public virtual DbSet<T_BT_LIGNE_GAMME2_OUINON> T_BT_LIGNE_GAMME2_OUINON { get; set; }

    public virtual DbSet<T_BT2> T_BT2 { get; set; }

    public virtual DbSet<T_BUDGET> T_BUDGET { get; set; }

    public virtual DbSet<T_BUTTON> T_BUTTON { get; set; }

    public virtual DbSet<T_CAL_PERS_COURANT> T_CAL_PERS_COURANT { get; set; }

    public virtual DbSet<T_CAL_UI> T_CAL_UI { get; set; }

    public virtual DbSet<T_CALENDRIER_CLIENT> T_CALENDRIER_CLIENT { get; set; }

    public virtual DbSet<T_CALENDRIER_FOURN> T_CALENDRIER_FOURN { get; set; }

    public virtual DbSet<T_CALENDRIER_INTERV> T_CALENDRIER_INTERV { get; set; }

    public virtual DbSet<T_CALENDRIER_UI> T_CALENDRIER_UI { get; set; }

    public virtual DbSet<T_CALIBRAGE> T_CALIBRAGE { get; set; }

    public virtual DbSet<T_CARBURANT> T_CARBURANT { get; set; }

    public virtual DbSet<T_CARTE_GRISE> T_CARTE_GRISE { get; set; }

    public virtual DbSet<T_CASE_CONFIG> T_CASE_CONFIG { get; set; }

    public virtual DbSet<T_CAUSE> T_CAUSE { get; set; }

    public virtual DbSet<T_CAYON_REFLEX_HISTO> T_CAYON_REFLEX_HISTO { get; set; }

    public virtual DbSet<T_CAYON_REFLEX_IP> T_CAYON_REFLEX_IP { get; set; }

    public virtual DbSet<T_CC> T_CC { get; set; }

    public virtual DbSet<T_CFG_MENU> T_CFG_MENU { get; set; }

    public virtual DbSet<T_CHAMP_FILTRE_PERSO> T_CHAMP_FILTRE_PERSO { get; set; }

    public virtual DbSet<T_CHAMP_FILTRE_PERSO_BOOL> T_CHAMP_FILTRE_PERSO_BOOL { get; set; }

    public virtual DbSet<T_CHAMP_FILTRE_PERSO_DATE> T_CHAMP_FILTRE_PERSO_DATE { get; set; }

    public virtual DbSet<T_CHAMP_FILTRE_PERSO_FLOAT> T_CHAMP_FILTRE_PERSO_FLOAT { get; set; }

    public virtual DbSet<T_CHAMP_FILTRE_PERSO_INT> T_CHAMP_FILTRE_PERSO_INT { get; set; }

    public virtual DbSet<T_CHAMP_FILTRE_PERSO_LIE> T_CHAMP_FILTRE_PERSO_LIE { get; set; }

    public virtual DbSet<T_CHAMP_FILTRE_PERSO_STR> T_CHAMP_FILTRE_PERSO_STR { get; set; }

    public virtual DbSet<T_CHAMPS> T_CHAMPS { get; set; }

    public virtual DbSet<T_CHAMPS_EXPORT_PERSO> T_CHAMPS_EXPORT_PERSO { get; set; }

    public virtual DbSet<T_CHANGE_CLIENT_UI> T_CHANGE_CLIENT_UI { get; set; }

    public virtual DbSet<T_CHGMT_CLIENT> T_CHGMT_CLIENT { get; set; }

    public virtual DbSet<T_CLE_PRIMAIRE> T_CLE_PRIMAIRE { get; set; }

    public virtual DbSet<T_CLIENT> T_CLIENT { get; set; }

    public virtual DbSet<T_CODE_COMPTABLE> T_CODE_COMPTABLE { get; set; }

    public virtual DbSet<T_CODE_POSITION> T_CODE_POSITION { get; set; }

    public virtual DbSet<T_COEFF_F_FOURN> T_COEFF_F_FOURN { get; set; }

    public virtual DbSet<T_COEFF_F_INTERV> T_COEFF_F_INTERV { get; set; }

    public virtual DbSet<T_COEFF_F_PIECE> T_COEFF_F_PIECE { get; set; }

    public virtual DbSet<T_COMMANDE> T_COMMANDE { get; set; }

    public virtual DbSet<T_COMMANDE2> T_COMMANDE2 { get; set; }

    public virtual DbSet<T_COMPTE_ACHAT_FOURN> T_COMPTE_ACHAT_FOURN { get; set; }

    public virtual DbSet<T_COMPTE_ACHAT_INTERV> T_COMPTE_ACHAT_INTERV { get; set; }

    public virtual DbSet<T_COMPTE_ACHAT_PIECE> T_COMPTE_ACHAT_PIECE { get; set; }

    public virtual DbSet<T_COMPTE_VENTE_FOURN> T_COMPTE_VENTE_FOURN { get; set; }

    public virtual DbSet<T_COMPTE_VENTE_INTERV> T_COMPTE_VENTE_INTERV { get; set; }

    public virtual DbSet<T_COMPTE_VENTE_PIECE> T_COMPTE_VENTE_PIECE { get; set; }

    public virtual DbSet<T_COND_REGL> T_COND_REGL { get; set; }

    public virtual DbSet<T_CONFIG_ACCUEIL> T_CONFIG_ACCUEIL { get; set; }

    public virtual DbSet<T_CONFLITS> T_CONFLITS { get; set; }

    public virtual DbSet<T_CONSIGNATION_BT> T_CONSIGNATION_BT { get; set; }

    public virtual DbSet<T_CONSTAT_EDL> T_CONSTAT_EDL { get; set; }

    public virtual DbSet<T_CONSTRUCTEUR> T_CONSTRUCTEUR { get; set; }

    public virtual DbSet<T_CONTEXT_AUDROS> T_CONTEXT_AUDROS { get; set; }

    public virtual DbSet<T_CONTRAT> T_CONTRAT { get; set; }

    public virtual DbSet<T_CONTRAT_CLIENT> T_CONTRAT_CLIENT { get; set; }

    public virtual DbSet<T_CORPS_MAIL_TYPE> T_CORPS_MAIL_TYPE { get; set; }

    public virtual DbSet<T_COUT_FIXE> T_COUT_FIXE { get; set; }

    public virtual DbSet<T_COUT_FIXE_BT> T_COUT_FIXE_BT { get; set; }

    public virtual DbSet<T_COUT_FIXE_CLIENT> T_COUT_FIXE_CLIENT { get; set; }

    public virtual DbSet<T_COUT_FIXE_DEVIS_F> T_COUT_FIXE_DEVIS_F { get; set; }

    public virtual DbSet<T_COUT_FIXE_FACTURE_F> T_COUT_FIXE_FACTURE_F { get; set; }

    public virtual DbSet<T_COUT_FIXE_UI> T_COUT_FIXE_UI { get; set; }

    public virtual DbSet<T_CPT_BT> T_CPT_BT { get; set; }

    public virtual DbSet<T_CPT_CARB> T_CPT_CARB { get; set; }

    public virtual DbSet<T_CPT_DI> T_CPT_DI { get; set; }

    public virtual DbSet<T_CPT_DIVERS> T_CPT_DIVERS { get; set; }

    public virtual DbSet<T_CPT_UI> T_CPT_UI { get; set; }

    public virtual DbSet<T_CRITIC> T_CRITIC { get; set; }

    public virtual DbSet<T_CSQ_EXPLOIT> T_CSQ_EXPLOIT { get; set; }

    public virtual DbSet<T_CUVE> T_CUVE { get; set; }

    public virtual DbSet<T_DA> T_DA { get; set; }

    public virtual DbSet<T_DAP> T_DAP { get; set; }

    public virtual DbSet<T_DECL_IP> T_DECL_IP { get; set; }

    public virtual DbSet<T_DECLENCH> T_DECLENCH { get; set; }

    public virtual DbSet<T_DECLENCH_APERIODIC> T_DECLENCH_APERIODIC { get; set; }

    public virtual DbSet<T_DECLENCHEUR_IP> T_DECLENCHEUR_IP { get; set; }

    public virtual DbSet<T_DECLENCHEUR_IP_CAL> T_DECLENCHEUR_IP_CAL { get; set; }

    public virtual DbSet<T_DECLENCHEUR_IP_CPT> T_DECLENCHEUR_IP_CPT { get; set; }

    public virtual DbSet<T_DEFAUT_LIGNE_BL> T_DEFAUT_LIGNE_BL { get; set; }

    public virtual DbSet<T_DEGDURGENCE> T_DEGDURGENCE { get; set; }

    public virtual DbSet<T_DEMANDEUR> T_DEMANDEUR { get; set; }

    public virtual DbSet<T_DEPRECIATION_AN> T_DEPRECIATION_AN { get; set; }

    public virtual DbSet<T_DETAIL_CAL_CLIENT> T_DETAIL_CAL_CLIENT { get; set; }

    public virtual DbSet<T_DETAIL_CAL_FOURN> T_DETAIL_CAL_FOURN { get; set; }

    public virtual DbSet<T_DETAIL_CAL_INTERV> T_DETAIL_CAL_INTERV { get; set; }

    public virtual DbSet<T_DETAIL_CAL_UI> T_DETAIL_CAL_UI { get; set; }

    public virtual DbSet<T_DETAIL_PLAGE_CLIENT> T_DETAIL_PLAGE_CLIENT { get; set; }

    public virtual DbSet<T_DETAIL_PLAGE_INTERV> T_DETAIL_PLAGE_INTERV { get; set; }

    public virtual DbSet<T_DETAIL_PLAGE_UI> T_DETAIL_PLAGE_UI { get; set; }

    public virtual DbSet<T_DETAIL_VALTAXE> T_DETAIL_VALTAXE { get; set; }

    public virtual DbSet<T_DEVICE> T_DEVICE { get; set; }

    public virtual DbSet<T_DEVIS> T_DEVIS { get; set; }

    public virtual DbSet<T_DEVIS_F> T_DEVIS_F { get; set; }

    public virtual DbSet<T_DI> T_DI { get; set; }

    public virtual DbSet<T_DOP> T_DOP { get; set; }

    public virtual DbSet<T_DROITS_DIS> T_DROITS_DIS { get; set; }

    public virtual DbSet<T_DS> T_DS { get; set; }

    public virtual DbSet<T_EDL> T_EDL { get; set; }

    public virtual DbSet<T_EFFET> T_EFFET { get; set; }

    public virtual DbSet<T_ENSEMBLE> T_ENSEMBLE { get; set; }

    public virtual DbSet<T_EQUIV_ETAT_MM_X3> T_EQUIV_ETAT_MM_X3 { get; set; }

    public virtual DbSet<T_EQUIV_ETAT_X3_MM> T_EQUIV_ETAT_X3_MM { get; set; }

    public virtual DbSet<T_EQUIV_FRAIS_X3_MM> T_EQUIV_FRAIS_X3_MM { get; set; }

    public virtual DbSet<T_ETAT_AVOIR> T_ETAT_AVOIR { get; set; }

    public virtual DbSet<T_ETAT_BL> T_ETAT_BL { get; set; }

    public virtual DbSet<T_ETAT_BR> T_ETAT_BR { get; set; }

    public virtual DbSet<T_ETAT_BR_CMDE> T_ETAT_BR_CMDE { get; set; }

    public virtual DbSet<T_ETAT_BS> T_ETAT_BS { get; set; }

    public virtual DbSet<T_ETAT_BT> T_ETAT_BT { get; set; }

    public virtual DbSet<T_ETAT_BT_CAYON_PRISERDV> T_ETAT_BT_CAYON_PRISERDV { get; set; }

    public virtual DbSet<T_ETAT_BT_CAYON_PRISERDV_DEPL> T_ETAT_BT_CAYON_PRISERDV_DEPL { get; set; }

    public virtual DbSet<T_ETAT_BT_CONCURRENT> T_ETAT_BT_CONCURRENT { get; set; }

    public virtual DbSet<T_ETAT_BT_NO_MODIF_PLANNING> T_ETAT_BT_NO_MODIF_PLANNING { get; set; }

    public virtual DbSet<T_ETAT_CMDE> T_ETAT_CMDE { get; set; }

    public virtual DbSet<T_ETAT_CMDE_2> T_ETAT_CMDE_2 { get; set; }

    public virtual DbSet<T_ETAT_CONTRAT_CLIENT> T_ETAT_CONTRAT_CLIENT { get; set; }

    public virtual DbSet<T_ETAT_DA> T_ETAT_DA { get; set; }

    public virtual DbSet<T_ETAT_DAP> T_ETAT_DAP { get; set; }

    public virtual DbSet<T_ETAT_DEVIS> T_ETAT_DEVIS { get; set; }

    public virtual DbSet<T_ETAT_DEVIS_F> T_ETAT_DEVIS_F { get; set; }

    public virtual DbSet<T_ETAT_DI> T_ETAT_DI { get; set; }

    public virtual DbSet<T_ETAT_DS> T_ETAT_DS { get; set; }

    public virtual DbSet<T_ETAT_FACTURATION> T_ETAT_FACTURATION { get; set; }

    public virtual DbSet<T_ETAT_FACTURATION_LIGNEBL> T_ETAT_FACTURATION_LIGNEBL { get; set; }

    public virtual DbSet<T_ETAT_FACTURE> T_ETAT_FACTURE { get; set; }

    public virtual DbSet<T_ETAT_FACTURE_BL> T_ETAT_FACTURE_BL { get; set; }

    public virtual DbSet<T_ETAT_FACTURE_F> T_ETAT_FACTURE_F { get; set; }

    public virtual DbSet<T_ETAT_FBLTE_DAP> T_ETAT_FBLTE_DAP { get; set; }

    public virtual DbSet<T_ETAT_FRAIS> T_ETAT_FRAIS { get; set; }

    public virtual DbSet<T_ETAT_HABILITATION_INTERV> T_ETAT_HABILITATION_INTERV { get; set; }

    public virtual DbSet<T_ETAT_INVENTAIRE> T_ETAT_INVENTAIRE { get; set; }

    public virtual DbSet<T_ETAT_LIGNE_BR> T_ETAT_LIGNE_BR { get; set; }

    public virtual DbSet<T_ETAT_LIGNE_DA> T_ETAT_LIGNE_DA { get; set; }

    public virtual DbSet<T_ETAT_LIGNE_DS> T_ETAT_LIGNE_DS { get; set; }

    public virtual DbSet<T_ETAT_MATRICULE> T_ETAT_MATRICULE { get; set; }

    public virtual DbSet<T_ETAT_REEXPORT_X3> T_ETAT_REEXPORT_X3 { get; set; }

    public virtual DbSet<T_ETAT_TRANSFERT> T_ETAT_TRANSFERT { get; set; }

    public virtual DbSet<T_ETAT_UI> T_ETAT_UI { get; set; }

    public virtual DbSet<T_ETAT_US_MAT> T_ETAT_US_MAT { get; set; }

    public virtual DbSet<T_ETAT_USER> T_ETAT_USER { get; set; }

    public virtual DbSet<T_EVAL_FOURN> T_EVAL_FOURN { get; set; }

    public virtual DbSet<T_EVAL_FOURN_BT> T_EVAL_FOURN_BT { get; set; }

    public virtual DbSet<T_EVAL_FOURN_CMDE> T_EVAL_FOURN_CMDE { get; set; }

    public virtual DbSet<T_EXPORT> T_EXPORT { get; set; }

    public virtual DbSet<T_EXPORT_PERSO> T_EXPORT_PERSO { get; set; }

    public virtual DbSet<T_FABRICANT_PIECE> T_FABRICANT_PIECE { get; set; }

    public virtual DbSet<T_FACT> T_FACT { get; set; }

    public virtual DbSet<T_FACT_VOLVO> T_FACT_VOLVO { get; set; }

    public virtual DbSet<T_FACTURE_F> T_FACTURE_F { get; set; }

    public virtual DbSet<T_FAISABILITE> T_FAISABILITE { get; set; }

    public virtual DbSet<T_FAMILLE_CHAMP> T_FAMILLE_CHAMP { get; set; }

    public virtual DbSet<T_FAMILLE_CLIENT> T_FAMILLE_CLIENT { get; set; }

    public virtual DbSet<T_FAMILLE_CNEH_1> T_FAMILLE_CNEH_1 { get; set; }

    public virtual DbSet<T_FAMILLE_CNEH_2> T_FAMILLE_CNEH_2 { get; set; }

    public virtual DbSet<T_FAMILLE_CNEH_3> T_FAMILLE_CNEH_3 { get; set; }

    public virtual DbSet<T_FAMILLE_CNEH_4> T_FAMILLE_CNEH_4 { get; set; }

    public virtual DbSet<T_FAMILLE_DA> T_FAMILLE_DA { get; set; }

    public virtual DbSet<T_FAMILLE_DEVIS> T_FAMILLE_DEVIS { get; set; }

    public virtual DbSet<T_FAMILLE_EDL> T_FAMILLE_EDL { get; set; }

    public virtual DbSet<T_FAMILLE_EVAL> T_FAMILLE_EVAL { get; set; }

    public virtual DbSet<T_FAMILLE_FACTURE> T_FAMILLE_FACTURE { get; set; }

    public virtual DbSet<T_FAMILLE_FOURN> T_FAMILLE_FOURN { get; set; }

    public virtual DbSet<T_FAMILLE_GAMME> T_FAMILLE_GAMME { get; set; }

    public virtual DbSet<T_FAMILLE_GAMME2> T_FAMILLE_GAMME2 { get; set; }

    public virtual DbSet<T_FAMILLE_HABILITATION> T_FAMILLE_HABILITATION { get; set; }

    public virtual DbSet<T_FAMILLE_INTERV> T_FAMILLE_INTERV { get; set; }

    public virtual DbSet<T_FAMILLE_IP> T_FAMILLE_IP { get; set; }

    public virtual DbSet<T_FAMILLE_PIECE> T_FAMILLE_PIECE { get; set; }

    public virtual DbSet<T_FAMILLE_SOUS_LIGNE_BT> T_FAMILLE_SOUS_LIGNE_BT { get; set; }

    public virtual DbSet<T_FAMILLE_UI> T_FAMILLE_UI { get; set; }

    public virtual DbSet<T_FAVORIS_RPT> T_FAVORIS_RPT { get; set; }

    public virtual DbSet<T_FERIES> T_FERIES { get; set; }

    public virtual DbSet<T_FILTRE_PERSO> T_FILTRE_PERSO { get; set; }

    public virtual DbSet<T_FONCTION> T_FONCTION { get; set; }

    public virtual DbSet<T_FONCTION_PERS> T_FONCTION_PERS { get; set; }

    public virtual DbSet<T_FOURN> T_FOURN { get; set; }

    public virtual DbSet<T_FOURNISSEUR_HABILITATION> T_FOURNISSEUR_HABILITATION { get; set; }

    public virtual DbSet<T_FRAIS> T_FRAIS { get; set; }

    public virtual DbSet<T_FRAIS_BL> T_FRAIS_BL { get; set; }

    public virtual DbSet<T_FRAIS_CMDE> T_FRAIS_CMDE { get; set; }

    public virtual DbSet<T_FRAIS_CMDE2> T_FRAIS_CMDE2 { get; set; }

    public virtual DbSet<T_FRAIS_DEVIS> T_FRAIS_DEVIS { get; set; }

    public virtual DbSet<T_GAMME> T_GAMME { get; set; }

    public virtual DbSet<T_GAMME2> T_GAMME2 { get; set; }

    public virtual DbSet<T_GESTION_SUPPRESSION> T_GESTION_SUPPRESSION { get; set; }

    public virtual DbSet<T_GROUPE> T_GROUPE { get; set; }

    public virtual DbSet<T_GROUPE_DEST_MAIL> T_GROUPE_DEST_MAIL { get; set; }

    public virtual DbSet<T_GTB_ALARME> T_GTB_ALARME { get; set; }

    public virtual DbSet<T_GTB_CPT> T_GTB_CPT { get; set; }

    public virtual DbSet<T_HABILITATION> T_HABILITATION { get; set; }

    public virtual DbSet<T_HABILITATION_INTERV> T_HABILITATION_INTERV { get; set; }

    public virtual DbSet<T_HISTO_BL> T_HISTO_BL { get; set; }

    public virtual DbSet<T_HISTO_CC_UI> T_HISTO_CC_UI { get; set; }

    public virtual DbSet<T_HISTO_CMDE2> T_HISTO_CMDE2 { get; set; }

    public virtual DbSet<T_HISTO_CPT> T_HISTO_CPT { get; set; }

    public virtual DbSet<T_HISTO_DA> T_HISTO_DA { get; set; }

    public virtual DbSet<T_HISTO_DEVIS> T_HISTO_DEVIS { get; set; }

    public virtual DbSet<T_HISTO_DOP> T_HISTO_DOP { get; set; }

    public virtual DbSet<T_HISTO_ETATS> T_HISTO_ETATS { get; set; }

    public virtual DbSet<T_HISTO_GOMME> T_HISTO_GOMME { get; set; }

    public virtual DbSet<T_HISTO_KM_PNEU> T_HISTO_KM_PNEU { get; set; }

    public virtual DbSet<T_HISTO_LIEU_UI> T_HISTO_LIEU_UI { get; set; }

    public virtual DbSet<T_HISTO_MAIL> T_HISTO_MAIL { get; set; }

    public virtual DbSet<T_HISTO_MESURE_UI> T_HISTO_MESURE_UI { get; set; }

    public virtual DbSet<T_HISTO_OBJ> T_HISTO_OBJ { get; set; }

    public virtual DbSet<T_HISTO_PRIXKM_VOLVO> T_HISTO_PRIXKM_VOLVO { get; set; }

    public virtual DbSet<T_HISTO_SE> T_HISTO_SE { get; set; }

    public virtual DbSet<T_HISTO_SMS> T_HISTO_SMS { get; set; }

    public virtual DbSet<T_HISTO_VERSIO> T_HISTO_VERSIO { get; set; }

    public virtual DbSet<T_IMG> T_IMG { get; set; }

    public virtual DbSet<T_IMG_ARBO> T_IMG_ARBO { get; set; }

    public virtual DbSet<T_INCOTERM> T_INCOTERM { get; set; }

    public virtual DbSet<T_INDIC_OBJ> T_INDIC_OBJ { get; set; }

    public virtual DbSet<T_INDIC_TAUX> T_INDIC_TAUX { get; set; }

    public virtual DbSet<T_INDICATEUR> T_INDICATEUR { get; set; }

    public virtual DbSet<T_INFO> T_INFO { get; set; }

    public virtual DbSet<T_INFO_ARBO> T_INFO_ARBO { get; set; }

    public virtual DbSet<T_INFO_IMAGE> T_INFO_IMAGE { get; set; }

    public virtual DbSet<T_INFO_INDICATEUR> T_INFO_INDICATEUR { get; set; }

    public virtual DbSet<T_INFO_LIST_INDIC> T_INFO_LIST_INDIC { get; set; }

    public virtual DbSet<T_INFO_TEXT> T_INFO_TEXT { get; set; }

    public virtual DbSet<T_INTERLOC_CLIENT> T_INTERLOC_CLIENT { get; set; }

    public virtual DbSet<T_INTERLOC_FOURN> T_INTERLOC_FOURN { get; set; }

    public virtual DbSet<T_INTERV> T_INTERV { get; set; }

    public virtual DbSet<T_INV_EQ> T_INV_EQ { get; set; }

    public virtual DbSet<T_INVENTAIRE> T_INVENTAIRE { get; set; }

    public virtual DbSet<T_IP> T_IP { get; set; }

    public virtual DbSet<T_ITEM_GAMME2> T_ITEM_GAMME2 { get; set; }

    public virtual DbSet<T_KIT> T_KIT { get; set; }

    public virtual DbSet<T_LANGUES_IHM> T_LANGUES_IHM { get; set; }

    public virtual DbSet<T_LGDIS> T_LGDIS { get; set; }

    public virtual DbSet<T_LIBELLES_CR> T_LIBELLES_CR { get; set; }

    public virtual DbSet<T_LIBRE> T_LIBRE { get; set; }

    public virtual DbSet<T_LIBRE_2> T_LIBRE_2 { get; set; }

    public virtual DbSet<T_LIBRE_3> T_LIBRE_3 { get; set; }

    public virtual DbSet<T_LIBRE_4> T_LIBRE_4 { get; set; }

    public virtual DbSet<T_LIBRE_5> T_LIBRE_5 { get; set; }

    public virtual DbSet<T_LIBRE_6> T_LIBRE_6 { get; set; }

    public virtual DbSet<T_LIBRE_7> T_LIBRE_7 { get; set; }

    public virtual DbSet<T_LIBRE_CMDE> T_LIBRE_CMDE { get; set; }

    public virtual DbSet<T_LIBRE_CMDE_2> T_LIBRE_CMDE_2 { get; set; }

    public virtual DbSet<T_LIBRE_HA_MAG> T_LIBRE_HA_MAG { get; set; }

    public virtual DbSet<T_LIBRE_HA1> T_LIBRE_HA1 { get; set; }

    public virtual DbSet<T_LIBRE_LIGNE_CMDE> T_LIBRE_LIGNE_CMDE { get; set; }

    public virtual DbSet<T_LIBRE_LIGNE_CMDE2> T_LIBRE_LIGNE_CMDE2 { get; set; }

    public virtual DbSet<T_LIBRE_LIGNE_CMDE3> T_LIBRE_LIGNE_CMDE3 { get; set; }

    public virtual DbSet<T_LIEN> T_LIEN { get; set; }

    public virtual DbSet<T_LIEN_ACHAT_DETVALTAXE> T_LIEN_ACHAT_DETVALTAXE { get; set; }

    public virtual DbSet<T_LIEN_ACTIONMAIL_MAIL> T_LIEN_ACTIONMAIL_MAIL { get; set; }

    public virtual DbSet<T_LIEN_BT_ARBO> T_LIEN_BT_ARBO { get; set; }

    public virtual DbSet<T_LIEN_BT_BPU> T_LIEN_BT_BPU { get; set; }

    public virtual DbSet<T_LIEN_BT_CMDE> T_LIEN_BT_CMDE { get; set; }

    public virtual DbSet<T_LIEN_BT_DEVIS_F> T_LIEN_BT_DEVIS_F { get; set; }

    public virtual DbSet<T_LIEN_BT_GAMME> T_LIEN_BT_GAMME { get; set; }

    public virtual DbSet<T_LIEN_BT_LIGNE_GAMME2_IMG> T_LIEN_BT_LIGNE_GAMME2_IMG { get; set; }

    public virtual DbSet<T_LIEN_BT_UI> T_LIEN_BT_UI { get; set; }

    public virtual DbSet<T_LIEN_CAL_CLIENT> T_LIEN_CAL_CLIENT { get; set; }

    public virtual DbSet<T_LIEN_CAL_FOURN> T_LIEN_CAL_FOURN { get; set; }

    public virtual DbSet<T_LIEN_CAL_INTERV> T_LIEN_CAL_INTERV { get; set; }

    public virtual DbSet<T_LIEN_CAL_UI> T_LIEN_CAL_UI { get; set; }

    public virtual DbSet<T_LIEN_CAUSE_EFFET> T_LIEN_CAUSE_EFFET { get; set; }

    public virtual DbSet<T_LIEN_CAUSE_REMEDE> T_LIEN_CAUSE_REMEDE { get; set; }

    public virtual DbSet<T_LIEN_CC_METIER> T_LIEN_CC_METIER { get; set; }

    public virtual DbSet<T_LIEN_CC_VISEUR> T_LIEN_CC_VISEUR { get; set; }

    public virtual DbSet<T_LIEN_CFG_MENU_BUTTON> T_LIEN_CFG_MENU_BUTTON { get; set; }

    public virtual DbSet<T_LIEN_CLIENT_ADRESSE> T_LIEN_CLIENT_ADRESSE { get; set; }

    public virtual DbSet<T_LIEN_CONSIGNATION_BT_UI> T_LIEN_CONSIGNATION_BT_UI { get; set; }

    public virtual DbSet<T_LIEN_CONSIGNATION_RESP_C> T_LIEN_CONSIGNATION_RESP_C { get; set; }

    public virtual DbSet<T_LIEN_CONSIGNATION_RESP_D> T_LIEN_CONSIGNATION_RESP_D { get; set; }

    public virtual DbSet<T_LIEN_CONSIGNATION_VALID_C> T_LIEN_CONSIGNATION_VALID_C { get; set; }

    public virtual DbSet<T_LIEN_CONSIGNATION_VALID_D> T_LIEN_CONSIGNATION_VALID_D { get; set; }

    public virtual DbSet<T_LIEN_CONTRAT_CLIENT_DEGDURG> T_LIEN_CONTRAT_CLIENT_DEGDURG { get; set; }

    public virtual DbSet<T_LIEN_CONTRAT_CLIENT_PIECE> T_LIEN_CONTRAT_CLIENT_PIECE { get; set; }

    public virtual DbSet<T_LIEN_CONTRAT_CLIENT_UI> T_LIEN_CONTRAT_CLIENT_UI { get; set; }

    public virtual DbSet<T_LIEN_CONTRAT_FOURN_DEM> T_LIEN_CONTRAT_FOURN_DEM { get; set; }

    public virtual DbSet<T_LIEN_CONTRAT_TITRE_BT> T_LIEN_CONTRAT_TITRE_BT { get; set; }

    public virtual DbSet<T_LIEN_CONTRAT_UI> T_LIEN_CONTRAT_UI { get; set; }

    public virtual DbSet<T_LIEN_DAP_TRANSFERT> T_LIEN_DAP_TRANSFERT { get; set; }

    public virtual DbSet<T_LIEN_DEVIS_ACHAT_DETVALTAXE> T_LIEN_DEVIS_ACHAT_DETVALTAXE { get; set; }

    public virtual DbSet<T_LIEN_DEVIS_F_BPU> T_LIEN_DEVIS_F_BPU { get; set; }

    public virtual DbSet<T_LIEN_DEVIS_F_CLI_DETVALTAXE> T_LIEN_DEVIS_F_CLI_DETVALTAXE { get; set; }

    public virtual DbSet<T_LIEN_DEVIS_F_DETVALTAXE> T_LIEN_DEVIS_F_DETVALTAXE { get; set; }

    public virtual DbSet<T_LIEN_DI_BT> T_LIEN_DI_BT { get; set; }

    public virtual DbSet<T_LIEN_DI_JH_INTERV_PREFERE> T_LIEN_DI_JH_INTERV_PREFERE { get; set; }

    public virtual DbSet<T_LIEN_DOP_FOURN> T_LIEN_DOP_FOURN { get; set; }

    public virtual DbSet<T_LIEN_EFFET_CAUSE> T_LIEN_EFFET_CAUSE { get; set; }

    public virtual DbSet<T_LIEN_EFFET_REMEDE> T_LIEN_EFFET_REMEDE { get; set; }

    public virtual DbSet<T_LIEN_EXPORT_CHAMPS> T_LIEN_EXPORT_CHAMPS { get; set; }

    public virtual DbSet<T_LIEN_FACT_F_CLI_DETVALTAXE> T_LIEN_FACT_F_CLI_DETVALTAXE { get; set; }

    public virtual DbSet<T_LIEN_FACT_F_DETVALTAXE> T_LIEN_FACT_F_DETVALTAXE { get; set; }

    public virtual DbSet<T_LIEN_FACTURE_F_BPU> T_LIEN_FACTURE_F_BPU { get; set; }

    public virtual DbSet<T_LIEN_FACTURE_F_BT> T_LIEN_FACTURE_F_BT { get; set; }

    public virtual DbSet<T_LIEN_FAM_PIECE_ZONES_LIBRES> T_LIEN_FAM_PIECE_ZONES_LIBRES { get; set; }

    public virtual DbSet<T_LIEN_FAM_UI_ZONES_LIBRES> T_LIEN_FAM_UI_ZONES_LIBRES { get; set; }

    public virtual DbSet<T_LIEN_FAMILLE_CHAMBRE> T_LIEN_FAMILLE_CHAMBRE { get; set; }

    public virtual DbSet<T_LIEN_FAMILLE_MATERIEL_EDL> T_LIEN_FAMILLE_MATERIEL_EDL { get; set; }

    public virtual DbSet<T_LIEN_FAMILLE_TRAV_GAMME> T_LIEN_FAMILLE_TRAV_GAMME { get; set; }

    public virtual DbSet<T_LIEN_FAMUI_CAUSE> T_LIEN_FAMUI_CAUSE { get; set; }

    public virtual DbSet<T_LIEN_FAMUI_EFFET> T_LIEN_FAMUI_EFFET { get; set; }

    public virtual DbSet<T_LIEN_FAMUI_TITREBT> T_LIEN_FAMUI_TITREBT { get; set; }

    public virtual DbSet<T_LIEN_FAMUI_TITREDI> T_LIEN_FAMUI_TITREDI { get; set; }

    public virtual DbSet<T_LIEN_FOURNISSEUR_ACTIV> T_LIEN_FOURNISSEUR_ACTIV { get; set; }

    public virtual DbSet<T_LIEN_FRAIS_CMD_DETVALTAXE> T_LIEN_FRAIS_CMD_DETVALTAXE { get; set; }

    public virtual DbSet<T_LIEN_FRAIS_LIGNE_BL> T_LIEN_FRAIS_LIGNE_BL { get; set; }

    public virtual DbSet<T_LIEN_FRAIS_LIGNE_CMDE> T_LIEN_FRAIS_LIGNE_CMDE { get; set; }

    public virtual DbSet<T_LIEN_FRAIS_LIGNE_CMDE2> T_LIEN_FRAIS_LIGNE_CMDE2 { get; set; }

    public virtual DbSet<T_LIEN_FRAIS_LIGNE_DEVIS> T_LIEN_FRAIS_LIGNE_DEVIS { get; set; }

    public virtual DbSet<T_LIEN_FRAIS2_CMD_DETVALTAXE> T_LIEN_FRAIS2_CMD_DETVALTAXE { get; set; }

    public virtual DbSet<T_LIEN_HAB_REQUISE_BT> T_LIEN_HAB_REQUISE_BT { get; set; }

    public virtual DbSet<T_LIEN_HAB_REQUISE_IP> T_LIEN_HAB_REQUISE_IP { get; set; }

    public virtual DbSet<T_LIEN_HAB_REQUISE_UI> T_LIEN_HAB_REQUISE_UI { get; set; }

    public virtual DbSet<T_LIEN_IP_BPU> T_LIEN_IP_BPU { get; set; }

    public virtual DbSet<T_LIEN_IP_GAMME> T_LIEN_IP_GAMME { get; set; }

    public virtual DbSet<T_LIEN_ITEM_GAMME2_IMG> T_LIEN_ITEM_GAMME2_IMG { get; set; }

    public virtual DbSet<T_LIEN_KIT_PIECE> T_LIEN_KIT_PIECE { get; set; }

    public virtual DbSet<T_LIEN_LC_DETVALTAXE> T_LIEN_LC_DETVALTAXE { get; set; }

    public virtual DbSet<T_LIEN_LIGNE_BT_ARBO> T_LIEN_LIGNE_BT_ARBO { get; set; }

    public virtual DbSet<T_LIEN_LIGNE_BT_UI> T_LIEN_LIGNE_BT_UI { get; set; }

    public virtual DbSet<T_LIEN_LIGNE_GAMME2_IMG> T_LIEN_LIGNE_GAMME2_IMG { get; set; }

    public virtual DbSet<T_LIEN_LIST_INDIC_INDIC> T_LIEN_LIST_INDIC_INDIC { get; set; }

    public virtual DbSet<T_LIEN_MATERIEL_CONSTAT_BT_EDL> T_LIEN_MATERIEL_CONSTAT_BT_EDL { get; set; }

    public virtual DbSet<T_LIEN_MESURE_BT> T_LIEN_MESURE_BT { get; set; }

    public virtual DbSet<T_LIEN_MESURE_IP> T_LIEN_MESURE_IP { get; set; }

    public virtual DbSet<T_LIEN_MESURE_IP_MODELE> T_LIEN_MESURE_IP_MODELE { get; set; }

    public virtual DbSet<T_LIEN_MESURE_UI> T_LIEN_MESURE_UI { get; set; }

    public virtual DbSet<T_LIEN_OI_FOURN> T_LIEN_OI_FOURN { get; set; }

    public virtual DbSet<T_LIEN_OI_MATIERE> T_LIEN_OI_MATIERE { get; set; }

    public virtual DbSet<T_LIEN_PIECE_PIECE_EQ> T_LIEN_PIECE_PIECE_EQ { get; set; }

    public virtual DbSet<T_LIEN_PIECE_UNITECMDE> T_LIEN_PIECE_UNITECMDE { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_BL> T_LIEN_PROFIL_ETAT_BL { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_BR> T_LIEN_PROFIL_ETAT_BR { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_BR_CMDE> T_LIEN_PROFIL_ETAT_BR_CMDE { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_BS> T_LIEN_PROFIL_ETAT_BS { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_BT> T_LIEN_PROFIL_ETAT_BT { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_CMDE> T_LIEN_PROFIL_ETAT_CMDE { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_CMDE_2> T_LIEN_PROFIL_ETAT_CMDE_2 { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_DA> T_LIEN_PROFIL_ETAT_DA { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_DEVIS> T_LIEN_PROFIL_ETAT_DEVIS { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_DEVIS_F> T_LIEN_PROFIL_ETAT_DEVIS_F { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_DI> T_LIEN_PROFIL_ETAT_DI { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_DS> T_LIEN_PROFIL_ETAT_DS { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_FACTURE> T_LIEN_PROFIL_ETAT_FACTURE { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_FACTURE_BL> T_LIEN_PROFIL_ETAT_FACTURE_BL { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_FACTURE_F> T_LIEN_PROFIL_ETAT_FACTURE_F { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_INVENTAIRE> T_LIEN_PROFIL_ETAT_INVENTAIRE { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_LIGNE_BR> T_LIEN_PROFIL_ETAT_LIGNE_BR { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_LIGNE_DA> T_LIEN_PROFIL_ETAT_LIGNE_DA { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_LIGNE_DEVIS> T_LIEN_PROFIL_ETAT_LIGNE_DEVIS { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_LIGNE_DS> T_LIEN_PROFIL_ETAT_LIGNE_DS { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_MATRICULE> T_LIEN_PROFIL_ETAT_MATRICULE { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_UI> T_LIEN_PROFIL_ETAT_UI { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_US_MAT> T_LIEN_PROFIL_ETAT_US_MAT { get; set; }

    public virtual DbSet<T_LIEN_RGP_UIS> T_LIEN_RGP_UIS { get; set; }

    public virtual DbSet<T_LIEN_SESSION_HAB_INTERV> T_LIEN_SESSION_HAB_INTERV { get; set; }

    public virtual DbSet<T_LIEN_SESSION_STOCK> T_LIEN_SESSION_STOCK { get; set; }

    public virtual DbSet<T_LIEN_SITE_BUDGET> T_LIEN_SITE_BUDGET { get; set; }

    public virtual DbSet<T_LIEN_SITE_CC> T_LIEN_SITE_CC { get; set; }

    public virtual DbSet<T_LIEN_SITE_CLIENT> T_LIEN_SITE_CLIENT { get; set; }

    public virtual DbSet<T_LIEN_SITE_DEMANDEUR> T_LIEN_SITE_DEMANDEUR { get; set; }

    public virtual DbSet<T_LIEN_SITE_FAMILLE_PIECE> T_LIEN_SITE_FAMILLE_PIECE { get; set; }

    public virtual DbSet<T_LIEN_SITE_FAMILLE_TRAV> T_LIEN_SITE_FAMILLE_TRAV { get; set; }

    public virtual DbSet<T_LIEN_SITE_FAMILLE_UI> T_LIEN_SITE_FAMILLE_UI { get; set; }

    public virtual DbSet<T_LIEN_SITE_FOURN> T_LIEN_SITE_FOURN { get; set; }

    public virtual DbSet<T_LIEN_SITE_INTERV> T_LIEN_SITE_INTERV { get; set; }

    public virtual DbSet<T_LIEN_SITE_LIEU> T_LIEN_SITE_LIEU { get; set; }

    public virtual DbSet<T_LIEN_SITE_MAGASIN> T_LIEN_SITE_MAGASIN { get; set; }

    public virtual DbSet<T_LIEN_SITE_SERVICE> T_LIEN_SITE_SERVICE { get; set; }

    public virtual DbSet<T_LIEN_SITE_TT> T_LIEN_SITE_TT { get; set; }

    public virtual DbSet<T_LIEN_SITE_TYPE_UI> T_LIEN_SITE_TYPE_UI { get; set; }

    public virtual DbSet<T_LIEN_SITE_UIS_AUTORISES> T_LIEN_SITE_UIS_AUTORISES { get; set; }

    public virtual DbSet<T_LIEN_SITE_UIS_INTERDITES> T_LIEN_SITE_UIS_INTERDITES { get; set; }

    public virtual DbSet<T_LIEN_SITE_UIS_OK> T_LIEN_SITE_UIS_OK { get; set; }

    public virtual DbSet<T_LIEN_SITE_USER> T_LIEN_SITE_USER { get; set; }

    public virtual DbSet<T_LIEN_SITE_UTILISATION> T_LIEN_SITE_UTILISATION { get; set; }

    public virtual DbSet<T_LIEN_SLA_CONTRAT_CLI> T_LIEN_SLA_CONTRAT_CLI { get; set; }

    public virtual DbSet<T_LIEN_TRANSFERT_MAG> T_LIEN_TRANSFERT_MAG { get; set; }

    public virtual DbSet<T_LIEN_TYPE_CHAMBRE> T_LIEN_TYPE_CHAMBRE { get; set; }

    public virtual DbSet<T_LIEN_TYPE_DEST_CORPS_MAIL> T_LIEN_TYPE_DEST_CORPS_MAIL { get; set; }

    public virtual DbSet<T_LIEN_TYPE_EXPORT_CHAMPS> T_LIEN_TYPE_EXPORT_CHAMPS { get; set; }

    public virtual DbSet<T_LIEN_TYPE_UI_ZONES_LIBRES> T_LIEN_TYPE_UI_ZONES_LIBRES { get; set; }

    public virtual DbSet<T_LIEN_UI_INTERV> T_LIEN_UI_INTERV { get; set; }

    public virtual DbSet<T_LIEN_USER_ALERTE_CONTRAT_C> T_LIEN_USER_ALERTE_CONTRAT_C { get; set; }

    public virtual DbSet<T_LIEN_USER_ALERTE_CONTRAT_F> T_LIEN_USER_ALERTE_CONTRAT_F { get; set; }

    public virtual DbSet<T_LIEN_USER_BUDGET> T_LIEN_USER_BUDGET { get; set; }

    public virtual DbSet<T_LIEN_USER_CFG_MENU> T_LIEN_USER_CFG_MENU { get; set; }

    public virtual DbSet<T_LIEN_USER_CONFIG_ACCUEIL> T_LIEN_USER_CONFIG_ACCUEIL { get; set; }

    public virtual DbSet<T_LIEN_USER_FAVORIS_RPT> T_LIEN_USER_FAVORIS_RPT { get; set; }

    public virtual DbSet<T_LIEN_USER_INDIC> T_LIEN_USER_INDIC { get; set; }

    public virtual DbSet<T_LIEN_USER_INDIC_OBJ> T_LIEN_USER_INDIC_OBJ { get; set; }

    public virtual DbSet<T_LIEN_USER_INDIC_TAUX> T_LIEN_USER_INDIC_TAUX { get; set; }

    public virtual DbSet<T_LIEN_USER_INTERV> T_LIEN_USER_INTERV { get; set; }

    public virtual DbSet<T_LIEN_USER_LISTES_GEN> T_LIEN_USER_LISTES_GEN { get; set; }

    public virtual DbSet<T_LIEN_USER_MAG> T_LIEN_USER_MAG { get; set; }

    public virtual DbSet<T_LIEN_USER_OBJ> T_LIEN_USER_OBJ { get; set; }

    public virtual DbSet<T_LIEN_USER_OLD_PWD> T_LIEN_USER_OLD_PWD { get; set; }

    public virtual DbSet<T_LIEN_USER_PREFILTRE> T_LIEN_USER_PREFILTRE { get; set; }

    public virtual DbSet<T_LIEN_USER_UI> T_LIEN_USER_UI { get; set; }

    public virtual DbSet<T_LIEN_VISEUR_VISA_CMDE> T_LIEN_VISEUR_VISA_CMDE { get; set; }

    public virtual DbSet<T_LIEN_VISEUR_VISA_DA> T_LIEN_VISEUR_VISA_DA { get; set; }

    public virtual DbSet<T_LIEN_VISEUR_VISA_DEVIS> T_LIEN_VISEUR_VISA_DEVIS { get; set; }

    public virtual DbSet<T_LIEN_VISEUR_VISA_DOP> T_LIEN_VISEUR_VISA_DOP { get; set; }

    public virtual DbSet<T_LIEN_ZO_ETAT_BT> T_LIEN_ZO_ETAT_BT { get; set; }

    public virtual DbSet<T_LIEN_ZO_TT_BT> T_LIEN_ZO_TT_BT { get; set; }

    public virtual DbSet<T_LIEU> T_LIEU { get; set; }

    public virtual DbSet<T_LIEUSTOCK> T_LIEUSTOCK { get; set; }

    public virtual DbSet<T_LIGNE_BL> T_LIGNE_BL { get; set; }

    public virtual DbSet<T_LIGNE_BL_PIECE> T_LIGNE_BL_PIECE { get; set; }

    public virtual DbSet<T_LIGNE_BR> T_LIGNE_BR { get; set; }

    public virtual DbSet<T_LIGNE_BR_CMDE> T_LIGNE_BR_CMDE { get; set; }

    public virtual DbSet<T_LIGNE_BR_CMDE_PIECE> T_LIGNE_BR_CMDE_PIECE { get; set; }

    public virtual DbSet<T_LIGNE_BR_MATRICULE> T_LIGNE_BR_MATRICULE { get; set; }

    public virtual DbSet<T_LIGNE_BR_PIECE> T_LIGNE_BR_PIECE { get; set; }

    public virtual DbSet<T_LIGNE_BS> T_LIGNE_BS { get; set; }

    public virtual DbSet<T_LIGNE_BS_MATRICULE> T_LIGNE_BS_MATRICULE { get; set; }

    public virtual DbSet<T_LIGNE_BS_PIECE> T_LIGNE_BS_PIECE { get; set; }

    public virtual DbSet<T_LIGNE_BT> T_LIGNE_BT { get; set; }

    public virtual DbSet<T_LIGNE_BT_ALERT> T_LIGNE_BT_ALERT { get; set; }

    public virtual DbSet<T_LIGNE_CMDE> T_LIGNE_CMDE { get; set; }

    public virtual DbSet<T_LIGNE_CMDE2> T_LIGNE_CMDE2 { get; set; }

    public virtual DbSet<T_LIGNE_CMDE2_PIECE> T_LIGNE_CMDE2_PIECE { get; set; }

    public virtual DbSet<T_LIGNE_DA> T_LIGNE_DA { get; set; }

    public virtual DbSet<T_LIGNE_DA_PIECE> T_LIGNE_DA_PIECE { get; set; }

    public virtual DbSet<T_LIGNE_DAP> T_LIGNE_DAP { get; set; }

    public virtual DbSet<T_LIGNE_DEVIS> T_LIGNE_DEVIS { get; set; }

    public virtual DbSet<T_LIGNE_DEVIS_F> T_LIGNE_DEVIS_F { get; set; }

    public virtual DbSet<T_LIGNE_DEVIS_F_FOURN> T_LIGNE_DEVIS_F_FOURN { get; set; }

    public virtual DbSet<T_LIGNE_DEVIS_F_INTERV> T_LIGNE_DEVIS_F_INTERV { get; set; }

    public virtual DbSet<T_LIGNE_DEVIS_F_PIECE> T_LIGNE_DEVIS_F_PIECE { get; set; }

    public virtual DbSet<T_LIGNE_DEVIS_PIECE> T_LIGNE_DEVIS_PIECE { get; set; }

    public virtual DbSet<T_LIGNE_DOP> T_LIGNE_DOP { get; set; }

    public virtual DbSet<T_LIGNE_DOP_PIECE> T_LIGNE_DOP_PIECE { get; set; }

    public virtual DbSet<T_LIGNE_DS> T_LIGNE_DS { get; set; }

    public virtual DbSet<T_LIGNE_DS_MATRICULE> T_LIGNE_DS_MATRICULE { get; set; }

    public virtual DbSet<T_LIGNE_DS_PIECE> T_LIGNE_DS_PIECE { get; set; }

    public virtual DbSet<T_LIGNE_EDL> T_LIGNE_EDL { get; set; }

    public virtual DbSet<T_LIGNE_EVAL> T_LIGNE_EVAL { get; set; }

    public virtual DbSet<T_LIGNE_EVAL_BT_MODELE> T_LIGNE_EVAL_BT_MODELE { get; set; }

    public virtual DbSet<T_LIGNE_EVAL_CMDE_MODELE> T_LIGNE_EVAL_CMDE_MODELE { get; set; }

    public virtual DbSet<T_LIGNE_EVAL_OBJ> T_LIGNE_EVAL_OBJ { get; set; }

    public virtual DbSet<T_LIGNE_FACT> T_LIGNE_FACT { get; set; }

    public virtual DbSet<T_LIGNE_FACT_CMDE> T_LIGNE_FACT_CMDE { get; set; }

    public virtual DbSet<T_LIGNE_FACT_CMDE_PIECE> T_LIGNE_FACT_CMDE_PIECE { get; set; }

    public virtual DbSet<T_LIGNE_FACTURE_F> T_LIGNE_FACTURE_F { get; set; }

    public virtual DbSet<T_LIGNE_FACTURE_F_CARB> T_LIGNE_FACTURE_F_CARB { get; set; }

    public virtual DbSet<T_LIGNE_FACTURE_F_FOURN> T_LIGNE_FACTURE_F_FOURN { get; set; }

    public virtual DbSet<T_LIGNE_FACTURE_F_INTERV> T_LIGNE_FACTURE_F_INTERV { get; set; }

    public virtual DbSet<T_LIGNE_FACTURE_F_PIECE> T_LIGNE_FACTURE_F_PIECE { get; set; }

    public virtual DbSet<T_LIGNE_GAMME2> T_LIGNE_GAMME2 { get; set; }

    public virtual DbSet<T_LIGNE_INV_EQ> T_LIGNE_INV_EQ { get; set; }

    public virtual DbSet<T_LIGNE_IP> T_LIGNE_IP { get; set; }

    public virtual DbSet<T_LIST_INDIC> T_LIST_INDIC { get; set; }

    public virtual DbSet<T_LOCK_OBJET> T_LOCK_OBJET { get; set; }

    public virtual DbSet<T_LOT> T_LOT { get; set; }

    public virtual DbSet<T_MAG_AUTORISES> T_MAG_AUTORISES { get; set; }

    public virtual DbSet<T_MAGASIN> T_MAGASIN { get; set; }

    public virtual DbSet<T_MAIL_DEST> T_MAIL_DEST { get; set; }

    public virtual DbSet<T_MATERIEL_EDL> T_MATERIEL_EDL { get; set; }

    public virtual DbSet<T_MATIERE> T_MATIERE { get; set; }

    public virtual DbSet<T_MATRICULE_PIECE> T_MATRICULE_PIECE { get; set; }

    public virtual DbSet<T_MESURE> T_MESURE { get; set; }

    public virtual DbSet<T_MESURE_UI> T_MESURE_UI { get; set; }

    public virtual DbSet<T_METIER> T_METIER { get; set; }

    public virtual DbSet<T_METIER_DI> T_METIER_DI { get; set; }

    public virtual DbSet<T_MODE_INVENTAIRE> T_MODE_INVENTAIRE { get; set; }

    public virtual DbSet<T_MODE_RECONDUCTION> T_MODE_RECONDUCTION { get; set; }

    public virtual DbSet<T_MODIF> T_MODIF { get; set; }

    public virtual DbSet<T_MODIF_FRAIS_LIGNESBT> T_MODIF_FRAIS_LIGNESBT { get; set; }

    public virtual DbSet<T_MODULES> T_MODULES { get; set; }

    public virtual DbSet<T_MONNAIE> T_MONNAIE { get; set; }

    public virtual DbSet<T_MOTIF_DI> T_MOTIF_DI { get; set; }

    public virtual DbSet<T_MVT> T_MVT { get; set; }

    public virtual DbSet<T_MVTS_UI> T_MVTS_UI { get; set; }

    public virtual DbSet<T_NATURE_ARRET> T_NATURE_ARRET { get; set; }

    public virtual DbSet<T_NAV> T_NAV { get; set; }

    public virtual DbSet<T_NBR_SECTION_INDIC> T_NBR_SECTION_INDIC { get; set; }

    public virtual DbSet<T_NOEUD> T_NOEUD { get; set; }

    public virtual DbSet<T_NOMENC> T_NOMENC { get; set; }

    public virtual DbSet<T_NOMENC_CTR> T_NOMENC_CTR { get; set; }

    public virtual DbSet<T_NOMENC_FOURN> T_NOMENC_FOURN { get; set; }

    public virtual DbSet<T_NOMENC_MATRICULE> T_NOMENC_MATRICULE { get; set; }

    public virtual DbSet<T_NOTE_EVAL> T_NOTE_EVAL { get; set; }

    public virtual DbSet<T_NUM_SERIE_PNEU> T_NUM_SERIE_PNEU { get; set; }

    public virtual DbSet<T_OBJ_ESCALADE> T_OBJ_ESCALADE { get; set; }

    public virtual DbSet<T_OBJECTIF> T_OBJECTIF { get; set; }

    public virtual DbSet<T_OCCUP_CHAMBRE> T_OCCUP_CHAMBRE { get; set; }

    public virtual DbSet<T_OI> T_OI { get; set; }

    public virtual DbSet<T_PARAMS_ACHAT> T_PARAMS_ACHAT { get; set; }

    public virtual DbSet<T_PARAMS_APPS> T_PARAMS_APPS { get; set; }

    public virtual DbSet<T_PARAMS_ARIBA> T_PARAMS_ARIBA { get; set; }

    public virtual DbSet<T_PARAMS_AUDROS> T_PARAMS_AUDROS { get; set; }

    public virtual DbSet<T_PARAMS_AX> T_PARAMS_AX { get; set; }

    public virtual DbSet<T_PARAMS_BT> T_PARAMS_BT { get; set; }

    public virtual DbSet<T_PARAMS_CMDE> T_PARAMS_CMDE { get; set; }

    public virtual DbSet<T_PARAMS_CO_SAGE100> T_PARAMS_CO_SAGE100 { get; set; }

    public virtual DbSet<T_PARAMS_COMPTE_USER> T_PARAMS_COMPTE_USER { get; set; }

    public virtual DbSet<T_PARAMS_COULEUR_ETAT> T_PARAMS_COULEUR_ETAT { get; set; }

    public virtual DbSet<T_PARAMS_DI> T_PARAMS_DI { get; set; }

    public virtual DbSet<T_PARAMS_FACTURATION> T_PARAMS_FACTURATION { get; set; }

    public virtual DbSet<T_PARAMS_GAMMES> T_PARAMS_GAMMES { get; set; }

    public virtual DbSet<T_PARAMS_GE> T_PARAMS_GE { get; set; }

    public virtual DbSet<T_PARAMS_GS> T_PARAMS_GS { get; set; }

    public virtual DbSet<T_PARAMS_IP> T_PARAMS_IP { get; set; }

    public virtual DbSet<T_PARAMS_LDAP> T_PARAMS_LDAP { get; set; }

    public virtual DbSet<T_PARAMS_LISTES_GEN> T_PARAMS_LISTES_GEN { get; set; }

    public virtual DbSet<T_PARAMS_MAGASINIER> T_PARAMS_MAGASINIER { get; set; }

    public virtual DbSet<T_PARAMS_MAIL> T_PARAMS_MAIL { get; set; }

    public virtual DbSet<T_PARAMS_MAIL_ETAT_BT> T_PARAMS_MAIL_ETAT_BT { get; set; }

    public virtual DbSet<T_PARAMS_NAV> T_PARAMS_NAV { get; set; }

    public virtual DbSet<T_PARAMS_PLANNING> T_PARAMS_PLANNING { get; set; }

    public virtual DbSet<T_PARAMS_RESSOURCES> T_PARAMS_RESSOURCES { get; set; }

    public virtual DbSet<T_PARAMS_RPT> T_PARAMS_RPT { get; set; }

    public virtual DbSet<T_PARAMS_SAGE300> T_PARAMS_SAGE300 { get; set; }

    public virtual DbSet<T_PARAMS_SMS> T_PARAMS_SMS { get; set; }

    public virtual DbSet<T_PARAMS_SPE> T_PARAMS_SPE { get; set; }

    public virtual DbSet<T_PARAMS_STOCK> T_PARAMS_STOCK { get; set; }

    public virtual DbSet<T_PARAMS_TYPE_MAIL> T_PARAMS_TYPE_MAIL { get; set; }

    public virtual DbSet<T_PARAMS_TYPE_MAIL_ETAT> T_PARAMS_TYPE_MAIL_ETAT { get; set; }

    public virtual DbSet<T_PARAMS_X3> T_PARAMS_X3 { get; set; }

    public virtual DbSet<T_PHOTO> T_PHOTO { get; set; }

    public virtual DbSet<T_PHOTO_PIECE> T_PHOTO_PIECE { get; set; }

    public virtual DbSet<T_PHOTO_UI> T_PHOTO_UI { get; set; }

    public virtual DbSet<T_PIECE> T_PIECE { get; set; }

    public virtual DbSet<T_PIECE_BPU> T_PIECE_BPU { get; set; }

    public virtual DbSet<T_PIECE_REF_CONST> T_PIECE_REF_CONST { get; set; }

    public virtual DbSet<T_PLAGE_CLIENT> T_PLAGE_CLIENT { get; set; }

    public virtual DbSet<T_PLAGE_INTERV> T_PLAGE_INTERV { get; set; }

    public virtual DbSet<T_PLAGE_UI> T_PLAGE_UI { get; set; }

    public virtual DbSet<T_POINT_PCVUE> T_POINT_PCVUE { get; set; }

    public virtual DbSet<T_POINT_TIME> T_POINT_TIME { get; set; }

    public virtual DbSet<T_POLITESSE> T_POLITESSE { get; set; }

    public virtual DbSet<T_POSITION_PNEU> T_POSITION_PNEU { get; set; }

    public virtual DbSet<T_POUVOIR> T_POUVOIR { get; set; }

    public virtual DbSet<T_PREV_OBJ> T_PREV_OBJ { get; set; }

    public virtual DbSet<T_PROFILE> T_PROFILE { get; set; }

    public virtual DbSet<T_REAPPRO> T_REAPPRO { get; set; }

    public virtual DbSet<T_RECAP_SYNCHRO> T_RECAP_SYNCHRO { get; set; }

    public virtual DbSet<T_RECEPTION> T_RECEPTION { get; set; }

    public virtual DbSet<T_REGION> T_REGION { get; set; }

    public virtual DbSet<T_REGLE_DI_TO_BT> T_REGLE_DI_TO_BT { get; set; }

    public virtual DbSet<T_REMEDE> T_REMEDE { get; set; }

    public virtual DbSet<T_RESP_AFFAIRES> T_RESP_AFFAIRES { get; set; }

    public virtual DbSet<T_RETOUR_SMS> T_RETOUR_SMS { get; set; }

    public virtual DbSet<T_RGP_UIS> T_RGP_UIS { get; set; }

    public virtual DbSet<T_RS> T_RS { get; set; }

    public virtual DbSet<T_SCANPAL> T_SCANPAL { get; set; }

    public virtual DbSet<T_SE> T_SE { get; set; }

    public virtual DbSet<T_SENS_VOIE> T_SENS_VOIE { get; set; }

    public virtual DbSet<T_SERVICE> T_SERVICE { get; set; }

    public virtual DbSet<T_SESSION_HABILITATION> T_SESSION_HABILITATION { get; set; }

    public virtual DbSet<T_SESSION_INV_EQ> T_SESSION_INV_EQ { get; set; }

    public virtual DbSet<T_SESSION_INVENTAIRE> T_SESSION_INVENTAIRE { get; set; }

    public virtual DbSet<T_SITE> T_SITE { get; set; }

    public virtual DbSet<T_SLA> T_SLA { get; set; }

    public virtual DbSet<T_SOCIETE> T_SOCIETE { get; set; }

    public virtual DbSet<T_SOCIETE_BT> T_SOCIETE_BT { get; set; }

    public virtual DbSet<T_SOUS_ENSEMBLE> T_SOUS_ENSEMBLE { get; set; }

    public virtual DbSet<T_SOUS_FAMILLE_PIECE> T_SOUS_FAMILLE_PIECE { get; set; }

    public virtual DbSet<T_SOUS_FAMILLE_PIECE_2> T_SOUS_FAMILLE_PIECE_2 { get; set; }

    public virtual DbSet<T_SOUS_LIGNE_BT> T_SOUS_LIGNE_BT { get; set; }

    public virtual DbSet<T_SPECIALITE> T_SPECIALITE { get; set; }

    public virtual DbSet<T_STOCK> T_STOCK { get; set; }

    public virtual DbSet<T_SYS_DB_MASTERKEY> T_SYS_DB_MASTERKEY { get; set; }

    public virtual DbSet<T_TABLE> T_TABLE { get; set; }

    public virtual DbSet<T_TEXT_CASE_PLANNING> T_TEXT_CASE_PLANNING { get; set; }

    public virtual DbSet<T_TEXT_INFOBULLE_PLANNING> T_TEXT_INFOBULLE_PLANNING { get; set; }

    public virtual DbSet<T_TITRE_BT> T_TITRE_BT { get; set; }

    public virtual DbSet<T_TITRE_DI> T_TITRE_DI { get; set; }

    public virtual DbSet<T_TMP_BIC> T_TMP_BIC { get; set; }

    public virtual DbSet<T_TMP_IMG> T_TMP_IMG { get; set; }

    public virtual DbSet<T_TMP_ZL> T_TMP_ZL { get; set; }

    public virtual DbSet<T_TPS_MACHINE> T_TPS_MACHINE { get; set; }

    public virtual DbSet<T_TVA> T_TVA { get; set; }

    public virtual DbSet<T_TYPE_ACTION> T_TYPE_ACTION { get; set; }

    public virtual DbSet<T_TYPE_ACTIV> T_TYPE_ACTIV { get; set; }

    public virtual DbSet<T_TYPE_ARRET> T_TYPE_ARRET { get; set; }

    public virtual DbSet<T_TYPE_BR_CMDE> T_TYPE_BR_CMDE { get; set; }

    public virtual DbSet<T_TYPE_CASE> T_TYPE_CASE { get; set; }

    public virtual DbSet<T_TYPE_CHAMP> T_TYPE_CHAMP { get; set; }

    public virtual DbSet<T_TYPE_COMMANDE> T_TYPE_COMMANDE { get; set; }

    public virtual DbSet<T_TYPE_CONFLIT> T_TYPE_CONFLIT { get; set; }

    public virtual DbSet<T_TYPE_CONTRAT> T_TYPE_CONTRAT { get; set; }

    public virtual DbSet<T_TYPE_CONTRAT_CLIENT> T_TYPE_CONTRAT_CLIENT { get; set; }

    public virtual DbSet<T_TYPE_CTR_VOLVO> T_TYPE_CTR_VOLVO { get; set; }

    public virtual DbSet<T_TYPE_DEST> T_TYPE_DEST { get; set; }

    public virtual DbSet<T_TYPE_DI> T_TYPE_DI { get; set; }

    public virtual DbSet<T_TYPE_ENTREE> T_TYPE_ENTREE { get; set; }

    public virtual DbSet<T_TYPE_EVAL> T_TYPE_EVAL { get; set; }

    public virtual DbSet<T_TYPE_EXPORT> T_TYPE_EXPORT { get; set; }

    public virtual DbSet<T_TYPE_GARANTIE> T_TYPE_GARANTIE { get; set; }

    public virtual DbSet<T_TYPE_INVENTAIRE> T_TYPE_INVENTAIRE { get; set; }

    public virtual DbSet<T_TYPE_INVENTAIRE_DEVIS_HA> T_TYPE_INVENTAIRE_DEVIS_HA { get; set; }

    public virtual DbSet<T_TYPE_LIEN_MAIL> T_TYPE_LIEN_MAIL { get; set; }

    public virtual DbSet<T_TYPE_LIEN_SMS> T_TYPE_LIEN_SMS { get; set; }

    public virtual DbSet<T_TYPE_MESURE> T_TYPE_MESURE { get; set; }

    public virtual DbSet<T_TYPE_MVT> T_TYPE_MVT { get; set; }

    public virtual DbSet<T_TYPE_OBJET> T_TYPE_OBJET { get; set; }

    public virtual DbSet<T_TYPE_PB_2> T_TYPE_PB_2 { get; set; }

    public virtual DbSet<T_TYPE_PB_3> T_TYPE_PB_3 { get; set; }

    public virtual DbSet<T_TYPE_PB1> T_TYPE_PB1 { get; set; }

    public virtual DbSet<T_TYPE_PRESENCE> T_TYPE_PRESENCE { get; set; }

    public virtual DbSet<T_TYPE_PRODUIT> T_TYPE_PRODUIT { get; set; }

    public virtual DbSet<T_TYPE_REPR_INDIC> T_TYPE_REPR_INDIC { get; set; }

    public virtual DbSet<T_TYPE_SESSION> T_TYPE_SESSION { get; set; }

    public virtual DbSet<T_TYPE_SORTIE> T_TYPE_SORTIE { get; set; }

    public virtual DbSet<T_TYPE_TRAV> T_TYPE_TRAV { get; set; }

    public virtual DbSet<T_TYPE_UI> T_TYPE_UI { get; set; }

    public virtual DbSet<T_UI> T_UI { get; set; }

    public virtual DbSet<T_UI_DEP_ANALYSE> T_UI_DEP_ANALYSE { get; set; }

    public virtual DbSet<T_UI_INFOS_LIBRES> T_UI_INFOS_LIBRES { get; set; }

    public virtual DbSet<T_UI_INFOS_TECH> T_UI_INFOS_TECH { get; set; }

    public virtual DbSet<T_UI_INTERDIT> T_UI_INTERDIT { get; set; }

    public virtual DbSet<T_UI_VOLVO> T_UI_VOLVO { get; set; }

    public virtual DbSet<T_UIS_AUTORISEES> T_UIS_AUTORISEES { get; set; }

    public virtual DbSet<T_UNIT_TPS> T_UNIT_TPS { get; set; }

    public virtual DbSet<T_UNITE_MESURE> T_UNITE_MESURE { get; set; }

    public virtual DbSet<T_UNITES> T_UNITES { get; set; }

    public virtual DbSet<T_URL_AUDROS> T_URL_AUDROS { get; set; }

    public virtual DbSet<T_USER> T_USER { get; set; }

    public virtual DbSet<T_UTILISATION> T_UTILISATION { get; set; }

    public virtual DbSet<T_VILLE> T_VILLE { get; set; }

    public virtual DbSet<T_VISEUR_HA> T_VISEUR_HA { get; set; }

    public virtual DbSet<T_ZC> T_ZC { get; set; }

    public virtual DbSet<T_ZO> T_ZO { get; set; }

    public virtual DbSet<T_ZONE> T_ZONE { get; set; }

    public virtual DbSet<T_ZONE_ANALYTIQUE_DEMANDEUR> T_ZONE_ANALYTIQUE_DEMANDEUR { get; set; }

    public virtual DbSet<T_ZONE_CRITIQUE> T_ZONE_CRITIQUE { get; set; }

    public virtual DbSet<T_ZONE_LIBRE_BT_CB> T_ZONE_LIBRE_BT_CB { get; set; }

    public virtual DbSet<T_ZONE_SE> T_ZONE_SE { get; set; }

    public virtual DbSet<T_ZONES_LIBRES_PIECE> T_ZONES_LIBRES_PIECE { get; set; }

    public virtual DbSet<T_ZONES_LIBRES_UI> T_ZONES_LIBRES_UI { get; set; }

    public virtual DbSet<T_ZONES_LIBRES_UI_2> T_ZONES_LIBRES_UI_2 { get; set; }

    public virtual DbSet<T_ZONES_LIBRES_UI_2_COMBO_1> T_ZONES_LIBRES_UI_2_COMBO_1 { get; set; }

    public virtual DbSet<T_ZONES_LIBRES_UI_2_COMBO_10> T_ZONES_LIBRES_UI_2_COMBO_10 { get; set; }

    public virtual DbSet<T_ZONES_LIBRES_UI_2_COMBO_2> T_ZONES_LIBRES_UI_2_COMBO_2 { get; set; }

    public virtual DbSet<T_ZONES_LIBRES_UI_2_COMBO_3> T_ZONES_LIBRES_UI_2_COMBO_3 { get; set; }

    public virtual DbSet<T_ZONES_LIBRES_UI_2_COMBO_4> T_ZONES_LIBRES_UI_2_COMBO_4 { get; set; }

    public virtual DbSet<T_ZONES_LIBRES_UI_2_COMBO_5> T_ZONES_LIBRES_UI_2_COMBO_5 { get; set; }

    public virtual DbSet<T_ZONES_LIBRES_UI_2_COMBO_6> T_ZONES_LIBRES_UI_2_COMBO_6 { get; set; }

    public virtual DbSet<T_ZONES_LIBRES_UI_2_COMBO_7> T_ZONES_LIBRES_UI_2_COMBO_7 { get; set; }

    public virtual DbSet<T_ZONES_LIBRES_UI_2_COMBO_8> T_ZONES_LIBRES_UI_2_COMBO_8 { get; set; }

    public virtual DbSet<T_ZONES_LIBRES_UI_2_COMBO_9> T_ZONES_LIBRES_UI_2_COMBO_9 { get; set; }

    public virtual DbSet<T_AFFAIRE> T_AFFAIRE { get; set; }

    public virtual DbSet<T_ARBO_UI_DEFAUT> T_ARBO_UI_DEFAUT { get; set; }

    public virtual DbSet<T_BLOCKED_IP> T_BLOCKED_IP { get; set; }

    public virtual DbSet<T_BRUTE_FORCE> T_BRUTE_FORCE { get; set; }

    public virtual DbSet<T_CAYON_CODE_COMPT> T_CAYON_CODE_COMPT { get; set; }

    public virtual DbSet<T_CENTRE_PROFIT> T_CENTRE_PROFIT { get; set; }

    public virtual DbSet<T_CHAMPS_ORDERBY_EXPORT_PERSO> T_CHAMPS_ORDERBY_EXPORT_PERSO { get; set; }

    public virtual DbSet<T_COEFF_F_CARB> T_COEFF_F_CARB { get; set; }

    public virtual DbSet<T_ETAT_CONTRAT_FOURN> T_ETAT_CONTRAT_FOURN { get; set; }

    public virtual DbSet<T_GEOLOC_TYPES> T_GEOLOC_TYPES { get; set; }

    public virtual DbSet<T_HISTO_FRAIS_STOCK> T_HISTO_FRAIS_STOCK { get; set; }

    public virtual DbSet<T_HISTO_NUMERO_BI> T_HISTO_NUMERO_BI { get; set; }

    public virtual DbSet<T_LIEN_EMETTEUR_ALERTE> T_LIEN_EMETTEUR_ALERTE { get; set; }

    public virtual DbSet<T_LIEN_IP_GROUPE_IPS> T_LIEN_IP_GROUPE_IPS { get; set; }

    public virtual DbSet<T_LIEN_OBJ_ESCALADE> T_LIEN_OBJ_ESCALADE { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_DAP> T_LIEN_PROFIL_ETAT_DAP { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_FBLTE_DAP> T_LIEN_PROFIL_ETAT_FBLTE_DAP { get; set; }

    public virtual DbSet<T_LIEN_PROFIL_ETAT_TRANSFERT> T_LIEN_PROFIL_ETAT_TRANSFERT { get; set; }

    public virtual DbSet<T_LIGNE_TAXE> T_LIGNE_TAXE { get; set; }

    public virtual DbSet<T_PARAMS_NUMERO_BI> T_PARAMS_NUMERO_BI { get; set; }

    public virtual DbSet<T_PARAMS_UI> T_PARAMS_UI { get; set; }

    public virtual DbSet<T_TAXE_COMPLEX> T_TAXE_COMPLEX { get; set; }

    public virtual DbSet<T_TYPE_ADR_CLIENT> T_TYPE_ADR_CLIENT { get; set; }

    public virtual DbSet<T_TYPE_REPARTITION_FRAIS> T_TYPE_REPARTITION_FRAIS { get; set; }

    public virtual DbSet<QREPORT_COMPLETION_TIME_KPI_REF> QREPORT_COMPLETION_TIME_KPI_REF { get; set; }

}

}

