
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_ACTION_EXPORT_XLS
{

    public int CLE_ACTION_EXPORT_XLS { get; set; }

    public Nullable<int> CLE_EXPORT { get; set; }

    public string CHEM_MODELE { get; set; }

    public string DIR_RES { get; set; }

    public string NOM_FICHIER_RES { get; set; }

    public string SUFFIXE_DH { get; set; }

    public string NOM_FEUILLE { get; set; }

    public string COL { get; set; }

    public Nullable<int> LIGNE { get; set; }

    public Nullable<int> CLE_RGP_UIS { get; set; }

    public string METTRE_ENTETE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
