
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_ACTIV
{

    public int NUM_ACTIV { get; set; }

    public Nullable<int> CLE_INTERV { get; set; }

    public Nullable<int> CLE_TYPE_ACTIV { get; set; }

    public string TITRE_ACTIV { get; set; }

    public Nullable<System.DateTime> DATE_ACTIV { get; set; }

    public Nullable<int> H_DEB { get; set; }

    public Nullable<int> H_FIN { get; set; }

    public Nullable<int> DUREE_ACTIV { get; set; }

    public string COMM { get; set; }

    public string ARCHIVE_ { get; set; }

    public string CHAINE_32_VIERGE { get; set; }

    public string CHAINE_32_VIERGE_2 { get; set; }

    public Nullable<int> INT_VIERGE { get; set; }

    public Nullable<int> INT2_VIERGE { get; set; }

    public Nullable<decimal> NUM_VIERGE { get; set; }

    public Nullable<decimal> NUM_VIERGE_2 { get; set; }

    public string BOOL_VIERGE { get; set; }

    public string BOOL_VIERGE_2 { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE_1 { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE_2 { get; set; }

    public Nullable<int> CLE_CC { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public Nullable<int> CLE_CONTRAT_CLIENT { get; set; }

}

}
