
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_ALERTE_MV_DESC
{

    public int CLE_ALERTE_MV { get; set; }

    public Nullable<System.DateTime> DATE_ALERTE { get; set; }

    public string TRAITEE { get; set; }

    public Nullable<System.DateTime> DATE_TTMT { get; set; }

    public string URGENCE { get; set; }

    public string EMETTEUR { get; set; }

    public string DESC_FAITS { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
