
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_APPRO_STOCK
{

    public int NUM_APPRO_STOCK { get; set; }

    public Nullable<int> CLE_STOCK { get; set; }

    public Nullable<int> CLE_FOURN { get; set; }

    public string STR_32_VIERGE { get; set; }

    public string CODE_PIECE { get; set; }

    public Nullable<decimal> PRIX_CMDE { get; set; }

    public Nullable<int> MONNAIE { get; set; }

    public Nullable<decimal> DELAI_MOYEN { get; set; }

    public Nullable<int> UNITE_CMDE { get; set; }

    public Nullable<decimal> COEFF { get; set; }

    public Nullable<System.DateTime> DATE_DERE_CMDE { get; set; }

    public string FOURN_PPAL { get; set; }

    public Nullable<decimal> PRIX_U { get; set; }

    public Nullable<System.DateTime> DATE_PRIXLE { get; set; }

    public Nullable<int> INT_VIERGE_1 { get; set; }

    public Nullable<int> INT_VIERGE_2 { get; set; }

    public Nullable<decimal> NUM_VIERGE_1 { get; set; }

    public Nullable<decimal> NUM_VIERGE_2 { get; set; }

    public string STR_32_VIERGE_1 { get; set; }

    public string STR_32_VIERGE_2 { get; set; }

    public Nullable<System.DateTime> DATE_1 { get; set; }

    public Nullable<System.DateTime> DATE_2 { get; set; }

    public string BOOL_VIERGE_1 { get; set; }

    public string BOOL_VIERGE_2 { get; set; }

    public Nullable<System.DateTime> DATE_VALIDITE_PRIX { get; set; }

    public Nullable<System.DateTime> DATE_DERE_MAJ { get; set; }

    public string COMM { get; set; }

    public Nullable<decimal> RATIO_UNITE_STOCK { get; set; }

    public Nullable<int> CLE_TVA { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string CODE_EAN_128 { get; set; }

    public Nullable<decimal> QTE_MIN_REAPPRO { get; set; }

}

}
