
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_ARRET
{

    public int CLE_ARRET { get; set; }

    public string NOM { get; set; }

    public string COMM { get; set; }

    public Nullable<int> DUREE { get; set; }

    public Nullable<System.DateTime> DH_CREATION { get; set; }

    public Nullable<int> CLE_USER { get; set; }

    public Nullable<int> CLE_NATURE { get; set; }

    public Nullable<int> CLE_TYPE_ARRET { get; set; }

    public Nullable<int> CLE_UI { get; set; }

    public Nullable<int> CLE_LIGNE_PROD { get; set; }

    public Nullable<int> HDEB { get; set; }

    public Nullable<int> HFIN { get; set; }

    public Nullable<decimal> POURC_FONC_UI { get; set; }

    public Nullable<decimal> POURC_FONC_LP { get; set; }

    public string ARRET_LP { get; set; }

    public Nullable<int> DUREE_ARRET_LP { get; set; }

    public Nullable<int> HDEB_ARRET_LP { get; set; }

    public Nullable<int> HFIN_ARRET_LP { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
