
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_BASE
{

    public int CLE_BASE { get; set; }

    public Nullable<int> CLE_PROJET { get; set; }

    public string CODE_BASE { get; set; }

    public string DATABASENAME { get; set; }

    public Nullable<int> LIEN_TYPE_BASE { get; set; }

    public string CHEMIN { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
