
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_BS
{

    public int CLE_BS { get; set; }

    public int CLE_UI { get; set; }

    public int CLE_BT { get; set; }

    public int CLE_DI { get; set; }

    public int CLE_CC { get; set; }

    public int CLE_MAG { get; set; }

    public int CLE_BUDGET { get; set; }

    public string COMM { get; set; }

    public int CLE_DEMANDEUR { get; set; }

    public Nullable<System.DateTime> DATE_BS { get; set; }

    public int CLE_ETAT_BS { get; set; }

    public string NUM_BS_AN { get; set; }

    public Nullable<int> CLE_DS { get; set; }

    public string ARCHIVE_ { get; set; }

    public string TITRE { get; set; }

    public Nullable<int> CLE_SERVICE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string FLAG_EXPORTE { get; set; }

    public Nullable<int> CLE_LIBRE_HA_MAG { get; set; }

}

}
