
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_BT2
{

    public int CLE_BT2 { get; set; }

    public Nullable<int> CLE_BT { get; set; }

    public Nullable<int> INT_1 { get; set; }

    public Nullable<int> INT_2 { get; set; }

    public Nullable<int> INT_3 { get; set; }

    public Nullable<int> INT_4 { get; set; }

    public Nullable<int> INT_5 { get; set; }

    public Nullable<int> INT_6 { get; set; }

    public Nullable<decimal> FLOAT_1 { get; set; }

    public Nullable<decimal> FLOAT_2 { get; set; }

    public Nullable<decimal> FLOAT_3 { get; set; }

    public Nullable<decimal> FLOAT_4 { get; set; }

    public Nullable<decimal> FLOAT_5 { get; set; }

    public Nullable<decimal> FLOAT_6 { get; set; }

    public Nullable<decimal> FLOAT_7 { get; set; }

    public Nullable<decimal> FLOAT_8 { get; set; }

    public Nullable<decimal> FLOAT_9 { get; set; }

    public Nullable<decimal> FLOAT_10 { get; set; }

    public Nullable<decimal> FLOAT_11 { get; set; }

    public Nullable<decimal> FLOAT_12 { get; set; }

    public string STR32_1 { get; set; }

    public string STR32_2 { get; set; }

    public string STR32_3 { get; set; }

    public string STR32_4 { get; set; }

    public string STR68_1 { get; set; }

    public string STR68_2 { get; set; }

    public string BLOB_1 { get; set; }

    public string BOOL_1 { get; set; }

    public string BOOL_2 { get; set; }

    public Nullable<int> CLE_UI { get; set; }

    public Nullable<int> CLE_LIEU { get; set; }

    public string BOOL_3 { get; set; }

    public string BOOL_4 { get; set; }

    public string BOOL_5 { get; set; }

    public string BOOL_6 { get; set; }

    public string BOOL_7 { get; set; }

    public string BOOL_8 { get; set; }

    public string BOOL_9 { get; set; }

    public string BOOL_10 { get; set; }

    public Nullable<System.DateTime> DATE_1 { get; set; }

    public Nullable<System.DateTime> DATE_2 { get; set; }

    public Nullable<System.DateTime> DATE_3 { get; set; }

    public Nullable<System.DateTime> DATE_4 { get; set; }

    public Nullable<System.DateTime> DATE_5 { get; set; }

    public string STR16_1 { get; set; }

    public string STR16_2 { get; set; }

    public string STR16_3 { get; set; }

    public string STR16_4 { get; set; }

    public string STR16_5 { get; set; }

    public string STR16_6 { get; set; }

    public string STR16_7 { get; set; }

    public string STR16_8 { get; set; }

    public string STR16_9 { get; set; }

    public string STR16_10 { get; set; }

    public string STR16_11 { get; set; }

    public string STR16_12 { get; set; }

    public string STR16_13 { get; set; }

    public string STR16_14 { get; set; }

    public string STR16_15 { get; set; }

    public string STR16_16 { get; set; }

    public string STR16_17 { get; set; }

    public string STR16_18 { get; set; }

    public string STR16_19 { get; set; }

    public string STR16_20 { get; set; }

    public string STR16_21 { get; set; }

    public string STR16_22 { get; set; }

    public string STR16_23 { get; set; }

    public string STR16_24 { get; set; }

    public string STR16_25 { get; set; }

    public string STR16_26 { get; set; }

    public string STR16_27 { get; set; }

    public string STR16_28 { get; set; }

    public string STR16_29 { get; set; }

    public string STR16_30 { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
