
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_BUDGET
{

    public int NUM_BUDGET { get; set; }

    public string DES_BUDGET { get; set; }

    public string CODE_BUDGET { get; set; }

    public Nullable<int> ANNEE { get; set; }

    public Nullable<decimal> INITIAL_ { get; set; }

    public Nullable<decimal> ENGAGE { get; set; }

    public Nullable<decimal> PROVISIONNE { get; set; }

    public Nullable<decimal> FACTURE { get; set; }

    public Nullable<decimal> DOUBLE_1 { get; set; }

    public Nullable<decimal> DOUBLE_2 { get; set; }

    public Nullable<decimal> DOUBLE_3 { get; set; }

    public Nullable<System.DateTime> DATE_DEB { get; set; }

    public string COMM { get; set; }

    public string FASS { get; set; }

    public string ARCHIVE_ { get; set; }

    public Nullable<int> CLE_MONNAIE { get; set; }

    public Nullable<int> INT_VIERGE_2 { get; set; }

    public string STR_VIERGE_1 { get; set; }

    public string STR_VIERGE_2 { get; set; }

    public string TYPE_BUDGET { get; set; }

    public Nullable<int> INT_VIERGE_1 { get; set; }

    public string BOOL_VIERGE_1 { get; set; }

    public string BOOL_VIERGE_2 { get; set; }

    public Nullable<decimal> TPS_TOTAL { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
