
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_CALIBRAGE
{

    public int CLE_CALIBRAGE { get; set; }

    public Nullable<int> CLE_BT { get; set; }

    public Nullable<int> INDICE { get; set; }

    public string STR_CAL1 { get; set; }

    public string STR_CAL2 { get; set; }

    public string STR_CAL3 { get; set; }

    public string STR_CAL4 { get; set; }

    public string STR_CAL5 { get; set; }

    public string STR_CAL6 { get; set; }

    public string STR_CAL7 { get; set; }

    public string STR_CAL8 { get; set; }

    public string STR_CAL9 { get; set; }

    public string STR_CAL10 { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
