
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_CAL_PERS_COURANT
{

    public int NUM_CAL_PERS_COURANT { get; set; }

    public string DES_CAL_PERS_COURANT { get; set; }

    public Nullable<int> SEMAINE_1 { get; set; }

    public Nullable<int> SEMAINE_2 { get; set; }

    public Nullable<int> SEMAINE_3 { get; set; }

    public Nullable<int> SEMAINE_4 { get; set; }

    public Nullable<int> SEMAINE_5 { get; set; }

    public Nullable<int> SEMAINE_6 { get; set; }

    public Nullable<int> SEMAINE_7 { get; set; }

    public Nullable<int> SEMAINE_8 { get; set; }

    public Nullable<int> SEMAINE_9 { get; set; }

    public Nullable<int> SEMAINE_10 { get; set; }

    public Nullable<int> SEMAINE_11 { get; set; }

    public Nullable<int> SEMAINE_12 { get; set; }

    public Nullable<int> SEMAINE_13 { get; set; }

    public Nullable<int> SEMAINE_14 { get; set; }

    public Nullable<int> SEMAINE_15 { get; set; }

    public Nullable<int> SEMAINE_16 { get; set; }

    public Nullable<int> SEMAINE_17 { get; set; }

    public Nullable<int> SEMAINE_18 { get; set; }

    public Nullable<int> SEMAINE_19 { get; set; }

    public Nullable<int> SEMAINE_20 { get; set; }

    public Nullable<int> SEMAINE_21 { get; set; }

    public Nullable<int> SEMAINE_22 { get; set; }

    public Nullable<int> SEMAINE_23 { get; set; }

    public Nullable<int> SEMAINE_24 { get; set; }

    public Nullable<int> SEMAINE_25 { get; set; }

    public Nullable<int> SEMAINE_26 { get; set; }

    public Nullable<int> SEMAINE_27 { get; set; }

    public Nullable<int> SEMAINE_28 { get; set; }

    public Nullable<int> SEMAINE_29 { get; set; }

    public Nullable<int> SEMAINE_30 { get; set; }

    public Nullable<int> SEMAINE_31 { get; set; }

    public Nullable<int> SEMAINE_32 { get; set; }

    public Nullable<int> SEMAINE_33 { get; set; }

    public Nullable<int> SEMAINE_34 { get; set; }

    public Nullable<int> SEMAINE_35 { get; set; }

    public Nullable<int> SEMAINE_36 { get; set; }

    public Nullable<int> SEMAINE_37 { get; set; }

    public Nullable<int> SEMAINE_38 { get; set; }

    public Nullable<int> SEMAINE_39 { get; set; }

    public Nullable<int> SEMAINE_40 { get; set; }

    public Nullable<int> SEMAINE_41 { get; set; }

    public Nullable<int> SEMAINE_42 { get; set; }

    public Nullable<int> SEMAINE_43 { get; set; }

    public Nullable<int> SEMAINE_44 { get; set; }

    public Nullable<int> SEMAINE_45 { get; set; }

    public Nullable<int> SEMAINE_46 { get; set; }

    public Nullable<int> SEMAINE_47 { get; set; }

    public Nullable<int> SEMAINE_48 { get; set; }

    public Nullable<int> SEMAINE_49 { get; set; }

    public Nullable<int> SEMAINE_50 { get; set; }

    public Nullable<int> SEMAINE_51 { get; set; }

    public Nullable<int> SEAMINE_52 { get; set; }

    public Nullable<int> SEMAINE_53 { get; set; }

    public string DATES_DEB { get; set; }

    public string DATES_FIN { get; set; }

    public Nullable<int> INT_VIERGE_1 { get; set; }

    public Nullable<int> INT_VIERGE_2 { get; set; }

    public string STR_32_VIERGE_1 { get; set; }

    public string ST_32_VIERGE_2 { get; set; }

    public string BOOL_VIERGE_1 { get; set; }

    public string BOOL_VIERGE_2 { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE_1 { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE_2 { get; set; }

    public Nullable<decimal> NUM_VIERGE_1 { get; set; }

    public Nullable<decimal> NUM_VIERGE_2 { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
