
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_CASE_CONFIG
{

    public int CLE_CASE_CONFIG { get; set; }

    public Nullable<int> CLE_CONFIG_ACCUEIL { get; set; }

    public Nullable<int> TOP_ { get; set; }

    public Nullable<int> LEFT_ { get; set; }

    public Nullable<int> WIDTH { get; set; }

    public Nullable<int> HEIGHT { get; set; }

    public Nullable<int> CLE_INFO { get; set; }

    public Nullable<int> CLE_TYPE_CASE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
