
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_CARBURANT
{

    public int NUM_CARB { get; set; }

    public Nullable<int> NUM_VEH { get; set; }

    public Nullable<int> CLE_UI { get; set; }

    public Nullable<decimal> QTE { get; set; }

    public Nullable<int> KM { get; set; }

    public Nullable<int> CLE_HISTO_CPT { get; set; }

    public Nullable<int> CLE_CUVE { get; set; }

    public Nullable<decimal> COUT_TOTAL_HT { get; set; }

    public Nullable<System.DateTime> DATE_PRISE { get; set; }

    public Nullable<int> CLE_CHAUFFEUR { get; set; }

    public Nullable<int> CLE_MONNAIE { get; set; }

    public Nullable<decimal> PRIX_LITRE { get; set; }

    public string PETIT_COMM { get; set; }

    public string STR_32 { get; set; }

    public string STR_128 { get; set; }

    public Nullable<int> INT_1 { get; set; }

    public Nullable<int> INT_2 { get; set; }

    public string BOOL_1 { get; set; }

    public Nullable<decimal> NUM_1 { get; set; }

    public Nullable<System.DateTime> DATE_1 { get; set; }

    public string STR_32_1 { get; set; }

    public string ARCHIVE_ { get; set; }

    public Nullable<int> CLE_CLIENT { get; set; }

    public string EXPORTE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
