
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_CC
{

    public int CLE_CC { get; set; }

    public string CODE_CC { get; set; }

    public string DESIGN_CC { get; set; }

    public string ADR_1 { get; set; }

    public string ADR_2 { get; set; }

    public string CP { get; set; }

    public string VILLE { get; set; }

    public string TEL { get; set; }

    public string FAX { get; set; }

    public Nullable<int> INT_VIERGE_1 { get; set; }

    public Nullable<int> INT_VIERGE_2 { get; set; }

    public string STR_32_VIERGE_1 { get; set; }

    public string STR_32_VIERGE_2 { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE_1 { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE_2 { get; set; }

    public string BOOL_VIERGE_1 { get; set; }

    public string BOOL_VIERGE_2 { get; set; }

    public Nullable<decimal> NUM_VIERGE_1 { get; set; }

    public Nullable<decimal> NUM_VIERGE_2 { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string ARCHIVE_ { get; set; }

}

}
