
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_CLIENT
{

    public int CLE_CLIENT { get; set; }

    public string NOM_CLIENT { get; set; }

    public string REF_CLIENT { get; set; }

    public string NOM_ADR { get; set; }

    public string ADR { get; set; }

    public string CP { get; set; }

    public string VILLE { get; set; }

    public string PAYS { get; set; }

    public string TEL { get; set; }

    public string FAX { get; set; }

    public string NOM_ADR_FACT { get; set; }

    public string ADR_FACT { get; set; }

    public string CP_FACT { get; set; }

    public string VILLE_FACT { get; set; }

    public string PAYS_FACT { get; set; }

    public string TEL_FACT { get; set; }

    public string FAX_FACT { get; set; }

    public Nullable<int> CLE_COND_REGL { get; set; }

    public Nullable<decimal> POURC_REMISE { get; set; }

    public string COMM_CLIENT { get; set; }

    public string FASS_CLIENT { get; set; }

    public string EMAIL_CLIENT { get; set; }

    public string WEB_CLIENT { get; set; }

    public string SIRET_CLIENT { get; set; }

    public string CODE_APE { get; set; }

    public Nullable<int> CLE_FAMILLE_CLIENT { get; set; }

    public Nullable<int> CLE_MONNAIE { get; set; }

    public string ARCHIVE_ { get; set; }

    public Nullable<int> CLE_COEFF_F_INTERV { get; set; }

    public Nullable<int> CLE_COEFF_F_PIECE { get; set; }

    public Nullable<int> CLE_COEFF_F_FOURN { get; set; }

    public string TVA_IC { get; set; }

    public Nullable<int> CLE_TVA { get; set; }

    public string COMM { get; set; }

    public string FASS { get; set; }

    public Nullable<int> CLE_COEFF_F_CARB { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public Nullable<decimal> X { get; set; }

    public Nullable<decimal> Y { get; set; }

    public Nullable<decimal> Z { get; set; }

}

}
