
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_COMMANDE
{

    public int NUM_COMMANDE { get; set; }

    public string TITRE_CMDE { get; set; }

    public Nullable<int> ETAT_CMDE { get; set; }

    public Nullable<int> CLE_FOURN { get; set; }

    public Nullable<int> CLE_CONDREGL { get; set; }

    public Nullable<System.DateTime> DATE_CMDE { get; set; }

    public string REF_FOURN { get; set; }

    public Nullable<int> CLE_MAG { get; set; }

    public Nullable<int> CLE_SERVICE { get; set; }

    public Nullable<decimal> DELAI_LIVRAISON { get; set; }

    public Nullable<decimal> REMISEHT { get; set; }

    public Nullable<decimal> FRAISHT { get; set; }

    public Nullable<decimal> TOTALHT { get; set; }

    public Nullable<decimal> TOTALTVA { get; set; }

    public Nullable<decimal> TOTALTTC { get; set; }

    public string FASS_CMDE { get; set; }

    public string COMM_CMDE { get; set; }

    public string ADR_LIVR { get; set; }

    public string CP_LIVR { get; set; }

    public string VILLE_LIVR { get; set; }

    public string TEL_LIVR { get; set; }

    public string FAX_LIVR { get; set; }

    public string ADR_FACT { get; set; }

    public string CP_FACT { get; set; }

    public string VILLE_FACT { get; set; }

    public string TEL_FACT { get; set; }

    public string FAX_FACT { get; set; }

    public Nullable<int> CLE_MONNAIE { get; set; }

    public string NUM_CMDE_AN { get; set; }

    public string ARCHIVE_ { get; set; }

    public Nullable<int> CLE_BUDGET { get; set; }

    public Nullable<int> INT_VIERGE_1 { get; set; }

    public Nullable<int> INT_VIERGE_2 { get; set; }

    public Nullable<decimal> DOUBLE_VIERGE_1 { get; set; }

    public string STR_32_VIERGE_1 { get; set; }

    public string ST_32_VIERGE_2 { get; set; }

    public string REMONTER_FRAIS_PR_PUMP { get; set; }

    public string BOOL_VIERGE { get; set; }

    public string NOM_LIVR { get; set; }

    public string NOM_FACT { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE_1 { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE_2 { get; set; }

    public string BOOL_VIERGE_2 { get; set; }

    public Nullable<decimal> NUM_VIERGE_1 { get; set; }

    public Nullable<decimal> NUM_VIERGE_2 { get; set; }

    public Nullable<int> CLE_LIBRE_CMDE { get; set; }

    public Nullable<int> CLE_LIBRE_CMDE_2 { get; set; }

    public Nullable<int> CLE_DEMANDEUR { get; set; }

    public Nullable<int> CLE_CC { get; set; }

    public string VISA_1 { get; set; }

    public string VISA_2 { get; set; }

    public string STR_BL { get; set; }

    public Nullable<int> CLE_RS_FACT { get; set; }

    public Nullable<int> CLE_RS_LIVR { get; set; }

    public string PAYS_FACT { get; set; }

    public string PAYS_LIVR { get; set; }

    public Nullable<int> CLE_AFFAIRE { get; set; }

    public Nullable<decimal> TOTAL_FRAIS_HT { get; set; }

    public Nullable<decimal> TOTAL_FRAIS_TTC { get; set; }

    public Nullable<int> CLE_TVA { get; set; }

    public string EXPORTE { get; set; }

    public string IMPUTATION { get; set; }

    public string ORDRE_INTERNE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string IDENTIFIANT_X3 { get; set; }

    public Nullable<int> CLE_CLIENT { get; set; }

    public Nullable<int> CLE_CONTRAT_CLIENT { get; set; }

    public Nullable<decimal> MONTANT_FACTURE { get; set; }

    public Nullable<int> CLE_ETAT_FACTURATION { get; set; }

    public Nullable<int> CLE_TYPE_COMMANDE { get; set; }

}

}
