
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_CONTRAT
{

    public int NUM_CONTRAT { get; set; }

    public string TITRE { get; set; }

    public Nullable<System.DateTime> DATEDEB { get; set; }

    public Nullable<System.DateTime> DATEFIN { get; set; }

    public Nullable<int> TYPECONTRAT { get; set; }

    public Nullable<System.DateTime> DATESIGNCONTRAT { get; set; }

    public Nullable<int> CLE_FOURN { get; set; }

    public string COMM_CONTRAT { get; set; }

    public string FASS_CONTRAT { get; set; }

    public Nullable<decimal> PRIX_CONTRAT { get; set; }

    public string ARCHIVE_ { get; set; }

    public Nullable<int> INT_VIERGE { get; set; }

    public Nullable<int> INT2_VIERGE { get; set; }

    public string STR_VIERGE { get; set; }

    public string STR2_VIERGE { get; set; }

    public string BOOL_VIERGE_1 { get; set; }

    public string BOOL_VIERGE_2 { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE_1 { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE_2 { get; set; }

    public Nullable<decimal> NUM_VIERGE_1 { get; set; }

    public Nullable<decimal> NUM_VIERGE_2 { get; set; }

    public Nullable<int> CLE_DECL { get; set; }

    public Nullable<int> SEUIL_ALERTE { get; set; }

    public Nullable<System.DateTime> DATE_PREC { get; set; }

    public Nullable<System.DateTime> DATE_PROCH { get; set; }

    public Nullable<System.DateTime> DATE_REELLE_DECL { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string CODE_CONTRAT { get; set; }

    public Nullable<int> CLE_ETAT { get; set; }

    public Nullable<int> CLE_GESTIONNAIRE { get; set; }

    public string MAIL_GESTIONNAIRE_ENVOYE { get; set; }

    public Nullable<System.DateTime> DATE_EXTENSION_CONTRAT { get; set; }

    public Nullable<decimal> SURCOUT_MENSUEL { get; set; }

    public Nullable<decimal> SURCOUT_UNITE_CPT { get; set; }

    public Nullable<int> CLE_DECLENCH { get; set; }

    public Nullable<int> VALEUR_COMPTEUR { get; set; }

    public string TOUT_LES_TITRES { get; set; }

    public string SURCOUT_MENSUEL_AN { get; set; }

    public string SURCOUT_UNITE_CPT_AN { get; set; }

}

}
