
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_DAP
{

    public int CLE_DAP { get; set; }

    public string CODE_AN_DAP { get; set; }

    public string TITRE_DAP { get; set; }

    public Nullable<System.DateTime> DATE_DEMANDE { get; set; }

    public Nullable<int> CLE_DEMANDEUR { get; set; }

    public Nullable<int> CLE_MAG_DEMANDEUR { get; set; }

    public Nullable<int> CLE_MAG_CIBLE { get; set; }

    public int CLE_ETAT_DAP { get; set; }

    public int CLE_ETAT_FBLTE_DAP { get; set; }

    public Nullable<System.DateTime> DATE_SOUHAIT { get; set; }

    public string COMM { get; set; }

    public Nullable<int> CLE_MAGASINIER { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
