
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_DECLENCHEUR_IP_CPT
{

    public int CLE_DECLENCHEUR_IP { get; set; }

    public int CLE_CPT_UI { get; set; }

    public Nullable<int> VAL_PREC { get; set; }

    public Nullable<int> VAL_PROCH { get; set; }

    public Nullable<int> VAL_REELLE { get; set; }

    public Nullable<int> PAS { get; set; }

    public Nullable<System.DateTime> DATE_PROCH_DECL_ESTIM { get; set; }

    public Nullable<int> SEMAINE_ESTIM { get; set; }

    public Nullable<int> MOIS_ESTIM { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
