
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_DEMANDEUR
{

    public int CLE_DEMANDEUR { get; set; }

    public string NOM_DEMANDEUR { get; set; }

    public string PRENOM_DEMANDEUR { get; set; }

    public string TEL { get; set; }

    public Nullable<int> CLE_SERVICE { get; set; }

    public Nullable<int> INT_VIERGE_1 { get; set; }

    public string BOOL_VIERGE_1 { get; set; }

    public string STR_32_VIERGE_1 { get; set; }

    public string MAIL_DEMANDEUR { get; set; }

    public string ARCHIVE_ { get; set; }

    public string EST_UN_VISEUR { get; set; }

    public string ADR { get; set; }

    public string CP { get; set; }

    public string VILLE { get; set; }

    public string FAX { get; set; }

    public Nullable<int> CLE_RESPONSABLE { get; set; }

    public string EST_UN_VISEUR_DI { get; set; }

    public string EST_UN_VISEUR_BT { get; set; }

    public string EST_UN_VISEUR_DAP { get; set; }

    public string EST_UN_VISEUR_CMDE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public Nullable<int> CLE_ZONE_ANALYTIQUE { get; set; }

    public string CODE_DEMANDEUR { get; set; }

}

}
