
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_DECLENCHEUR_IP
{

    public int CLE_DECLENCHEUR_IP { get; set; }

    public int CLE_DECLENCHEUR { get; set; }

    public int CLE_IP { get; set; }

    public Nullable<System.DateTime> DATE_PREC_DECL { get; set; }

    public Nullable<int> SEUIL_DECLENCH { get; set; }

    public Nullable<int> INDICE { get; set; }

    public Nullable<int> DELTA_IP_LIEE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
