
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_DOP
{

    public int CLE_DOP { get; set; }

    public string NUM_DOP_AN { get; set; }

    public string TITRE { get; set; }

    public Nullable<System.DateTime> DATE_DOP { get; set; }

    public string COMM_DOP { get; set; }

    public string LE_PLUS_RAPIDE { get; set; }

    public string LE_MOINS_CHER { get; set; }

    public string ARCHIVE_ { get; set; }

    public Nullable<int> CLE_MAG { get; set; }

    public Nullable<int> CLE_BUDGET { get; set; }

    public Nullable<int> CLE_CC { get; set; }

    public Nullable<int> CLE_UI { get; set; }

    public Nullable<int> CLE_BT { get; set; }

    public Nullable<int> CLE_VISA_1 { get; set; }

    public Nullable<int> CLE_VISA_2 { get; set; }

    public string NOM_LIVR { get; set; }

    public string ADR_LIVR { get; set; }

    public string CP_LIVR { get; set; }

    public string VILLE_LIVR { get; set; }

    public string PAYS_LIVR { get; set; }

    public string TEL_LIVR { get; set; }

    public string FAX_LIVR { get; set; }

    public string NOM_FACT { get; set; }

    public string ADR_FACT { get; set; }

    public string CP_FACT { get; set; }

    public string VILLE_FACT { get; set; }

    public string PAYS_FACT { get; set; }

    public string TEL_FACT { get; set; }

    public string FAX_FACT { get; set; }

    public string FASS { get; set; }

    public Nullable<decimal> POURCENTAGE_TAXE { get; set; }

    public string COMM { get; set; }

    public Nullable<int> CLE_DEMANDEUR { get; set; }

    public Nullable<int> CLE_SERVICE { get; set; }

    public Nullable<int> CLE_ORIGINE { get; set; }

    public Nullable<int> CLE_VISEUR_1 { get; set; }

    public Nullable<int> CLE_VISEUR_2 { get; set; }

    public Nullable<int> DELAI_MAX { get; set; }

    public Nullable<int> DELAI_MIN { get; set; }

    public Nullable<int> CLE_TVA { get; set; }

    public Nullable<int> CLE_COND_LIVR { get; set; }

    public string IMPRIME { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string COMM_SUR_EDITION { get; set; }

    public Nullable<int> CLE_DA { get; set; }

    public string FLAG_EXPORTE { get; set; }

    public Nullable<int> CLE_LIBRE_HA_MAG { get; set; }

}

}
