
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_DROITS_DIS
{

    public int CLE_DROIT { get; set; }

    public string NOM_LIBELLE { get; set; }

    public string NOM_FICHE { get; set; }

    public Nullable<int> CLE_PROFILE { get; set; }

    public string VISIBLE { get; set; }

    public string MODIFIABLE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
