
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_EDL
{

    public int CLE_EDL { get; set; }

    public string EST_MODELE { get; set; }

    public string TITRE { get; set; }

    public Nullable<System.DateTime> DATE_EDL { get; set; }

    public Nullable<int> CLE_UI { get; set; }

    public string TERMINE_ { get; set; }

    public string ARCHIVE_ { get; set; }

    public string FASS { get; set; }

    public string COMM { get; set; }

    public string COMM_SUR_SCAN { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
