
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_EXPORT_PERSO
{

    public int CLE_EXPORT_PERSO { get; set; }

    public string NOM_EXPORT_PERSO { get; set; }

    public Nullable<int> LIEN_TYPE_EXPORT { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE3 { get; set; }

    public string REQUETE { get; set; }

    public string CLAUSE { get; set; }

    public Nullable<int> LIEN_BASE { get; set; }

    public string CREE_PAR { get; set; }

    public Nullable<System.DateTime> DATE_CREATION { get; set; }

    public Nullable<System.DateTime> DATE_MODIF { get; set; }

    public string REQUETE_FINALE { get; set; }

    public string EXPORT_PAR_DEFAUT { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string EXPORT_MODELE { get; set; }

    public string REQUETTE_PERSONNALISEE { get; set; }

}

}
