
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_FACT_VOLVO
{

    public int CLE_FACT { get; set; }

    public int NUM_UI { get; set; }

    public Nullable<System.DateTime> DATE_FACT { get; set; }

    public Nullable<int> NOMBRE_KM { get; set; }

    public Nullable<decimal> PRIX_KM { get; set; }

    public Nullable<decimal> TOTAL_FACT { get; set; }

    public string NUM_OR { get; set; }

    public string NUM_FACT { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
