
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_FAMILLE_UI
{

    public int CLE_FAM { get; set; }

    public string LIBELLE_FAM { get; set; }

    public string CODE_FAM { get; set; }

    public string TYPE_COUT { get; set; }

    public Nullable<decimal> COUT { get; set; }

    public Nullable<decimal> COUT_LAVAGE { get; set; }

    public Nullable<decimal> COEFF_CONSO { get; set; }

    public Nullable<int> LIBRE_INT_1 { get; set; }

    public Nullable<int> LIBRE_INT_2 { get; set; }

    public string LIBRE_STR_32 { get; set; }

    public string LIBRE_STR_32_2 { get; set; }

    public Nullable<decimal> LIBRE_NUMERIC { get; set; }

    public Nullable<decimal> LIBRE_NUMERIC_2 { get; set; }

    public string BOOL_VIERGE_1 { get; set; }

    public string BOOL_VIERGE_2 { get; set; }

    public Nullable<int> INDICE_IMG { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
