
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_FOURN
{

    public int CLE_FOURNISSEUR { get; set; }

    public string NOM { get; set; }

    public string REF { get; set; }

    public string TEL1 { get; set; }

    public string TEL2 { get; set; }

    public string TEL3 { get; set; }

    public string INTERLOC1 { get; set; }

    public string INTERLOC2 { get; set; }

    public string INTERLOC3 { get; set; }

    public string FAX1 { get; set; }

    public string FAX2 { get; set; }

    public string FAX3 { get; set; }

    public string EMAIL1 { get; set; }

    public string EMAIL2 { get; set; }

    public string EMAIL3 { get; set; }

    public string ADR { get; set; }

    public string CP { get; set; }

    public string VILLE { get; set; }

    public Nullable<int> CLE_CAL_PERS { get; set; }

    public Nullable<int> CLE_CAL_PERS_2 { get; set; }

    public string PORTABLE1 { get; set; }

    public string PORTABLE2 { get; set; }

    public string PORTABLE3 { get; set; }

    public Nullable<int> CLE_FAMILLE_FOURN { get; set; }

    public string COMM { get; set; }

    public string FASS { get; set; }

    public Nullable<int> INTERLOC_PPAL { get; set; }

    public string ARCHIVE_ { get; set; }

    public Nullable<int> CLE_MONNAIE { get; set; }

    public Nullable<int> INT_VIERGE_1 { get; set; }

    public Nullable<int> INT_VIERGE_2 { get; set; }

    public string STR32_VIERGE_1 { get; set; }

    public string ST32_VIERGE_2 { get; set; }

    public string BOOL_VIERGE { get; set; }

    public string PAYS { get; set; }

    public Nullable<int> CLE_CONDREGL { get; set; }

    public string BOOL_VIERGE_2 { get; set; }

    public Nullable<decimal> NUM_VIERGE_1 { get; set; }

    public Nullable<decimal> NUM_VIERGE_2 { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE_1 { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE_2 { get; set; }

    public string WEB { get; set; }

    public string MAIL { get; set; }

    public Nullable<int> CODE_INT_FOURN { get; set; }

    public string ADR1 { get; set; }

    public string ADR2 { get; set; }

    public string ADR3 { get; set; }

    public Nullable<int> CLE_COEFF_F_FOURN { get; set; }

    public Nullable<decimal> COEFF { get; set; }

    public Nullable<int> CLE_IMAGE { get; set; }

    public Nullable<int> SEUL_FRAIS_PORT_GRATIS { get; set; }

    public Nullable<int> SEUIL_FRAIS_ADMIN_PAYANTS { get; set; }

    public Nullable<int> CLE_COMPTE_ACHAT { get; set; }

    public Nullable<int> CLE_COMPTE_VENTE { get; set; }

    public Nullable<int> CLE_INCOTERM { get; set; }

    public Nullable<int> CLE_COND_LIVR { get; set; }

    public Nullable<decimal> POURC_ACOMPTE { get; set; }

    public string ADR_2 { get; set; }

    public string ADR_21 { get; set; }

    public string ADR_22 { get; set; }

    public string ADR_23 { get; set; }

    public string CP_2 { get; set; }

    public string VILLE_2 { get; set; }

    public string PAYS_2 { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public Nullable<int> CLE_VILLE { get; set; }

    public Nullable<int> CLE_REGION { get; set; }

    public Nullable<decimal> X { get; set; }

    public Nullable<decimal> Y { get; set; }

    public Nullable<decimal> Z { get; set; }

    public Nullable<int> CLE_VILLE_2 { get; set; }

    public Nullable<int> CLE_REGION_2 { get; set; }

    public Nullable<int> CLE_TVA { get; set; }

    public string EST_ADHERENT { get; set; }

    public string EST_PARTENAIRE { get; set; }

    public string EST_SOUSTRAITANT { get; set; }

}

}
