
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_GAMME
{

    public int NUM_GAMME { get; set; }

    public string NOM { get; set; }

    public string STR_128 { get; set; }

    public string STR_32 { get; set; }

    public string BOOL_1 { get; set; }

    public Nullable<int> LIEN_FAMILLE_GAMME { get; set; }

    public Nullable<int> INT_2 { get; set; }

    public Nullable<decimal> NUM_1 { get; set; }

    public Nullable<decimal> NUM_2 { get; set; }

    public Nullable<int> CLE_IMAGE { get; set; }

    public string COMM { get; set; }

    public Nullable<int> CLE_CPT { get; set; }

    public Nullable<decimal> VAL_MIN { get; set; }

    public Nullable<decimal> VAL_MAX { get; set; }

    public Nullable<decimal> VAL_SAISIE { get; set; }

    public Nullable<System.DateTime> DATE_SAISIE { get; set; }

    public string GENERER_BT_SI_VAL_KO { get; set; }

    public string TEXT_2 { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
