
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_GTB_ALARME
{

    public int CLE_GTB_ALARME { get; set; }

    public string CODE_POINT { get; set; }

    public Nullable<System.DateTime> DATE_GTB_ALARME { get; set; }

    public string HEURE_GTB_ALARME { get; set; }

    public string TITRE_GTB_ALARME { get; set; }

    public string TYPE_GTB_ALARME { get; set; }

    public string COMM_GTB_ALARME { get; set; }

    public string UNITE_GTB_CPT_2 { get; set; }

    public string TRAITE_GTB_ALARME { get; set; }

    public Nullable<int> INT_1_ALARME { get; set; }

    public string STR_32_ALARME { get; set; }

    public string STR_128_ALARME { get; set; }

    public string BOOL_1_ALARME { get; set; }

    public Nullable<System.DateTime> DATE_1_ALARME { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
