
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_HABILITATION
{

    public int CLE_HABILITATION { get; set; }

    public string CODE_HABILITATION { get; set; }

    public string LIBELLE_HABILITATION { get; set; }

    public string DESC_HABILITATION { get; set; }

    public Nullable<int> CLE_FAMILLE { get; set; }

    public string FASS { get; set; }

    public Nullable<int> CLE_DECL { get; set; }

    public Nullable<int> SEUIL_ALERTE { get; set; }

    public string ARCHIVE_ { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
