
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_HISTO_KM_PNEU
{

    public int CLE_HISTO_KM_PNEU { get; set; }

    public int CLE_MATRICULE_PIECE { get; set; }

    public Nullable<int> CLE_UI { get; set; }

    public Nullable<System.DateTime> DATE_HISTO_KM_PNEU { get; set; }

    public Nullable<decimal> ANCIEN { get; set; }

    public Nullable<decimal> NOUVEAU { get; set; }

    public Nullable<int> CLE_BT { get; set; }

    public Nullable<int> CLE_LIGNE_BT { get; set; }

    public Nullable<int> CLE_HISTO_CPT { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
