
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_HISTO_SMS
{

    public int CLE_HISTO_SMS { get; set; }

    public Nullable<int> CLE_TYPE_LIEN_SMS { get; set; }

    public Nullable<int> CLE_LIEN { get; set; }

    public Nullable<System.DateTime> DATE_ENVOI_SMS { get; set; }

    public string MESS_SMS { get; set; }

    public Nullable<int> CLE_USER_EXP_SMS { get; set; }

    public string NUM_TEL_DEST_SMS { get; set; }

    public string SMS_ENVOYE { get; set; }

    public string SMS_RECU { get; set; }

    public string MESS_ERREUR { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string IDCAMPAGNESMS { get; set; }

    public Nullable<int> NB_RETOUR { get; set; }

    public string NE_PAS_TRAITER { get; set; }

    public Nullable<int> CLE_LIGNE_BT_SMS { get; set; }

}

}
