
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_HISTO_FRAIS_STOCK
{

    public int CLE_MODIF_FRAIS { get; set; }

    public Nullable<System.DateTime> DATE_ { get; set; }

    public Nullable<int> CLE_USER { get; set; }

    public Nullable<int> CLE_STOCK { get; set; }

    public Nullable<int> CLE_LOT { get; set; }

    public Nullable<decimal> OLD_FRAIS_LOT { get; set; }

    public Nullable<decimal> NEW_FRAIS_LOT { get; set; }

    public Nullable<decimal> OLD_FRAIS_STOCK { get; set; }

    public Nullable<decimal> NEW_FRAIS_STOCK { get; set; }

    public Nullable<decimal> DELTA_FRAIS_PAR_PIECE { get; set; }

    public Nullable<int> QTE_CONSO { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
