
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_HISTO_SE
{

    public int CLE_HISTO_SE { get; set; }

    public Nullable<System.DateTime> DATE_SE { get; set; }

    public int CLE_USER_CONNECT { get; set; }

    public string NOM_USER_CONNECT { get; set; }

    public string PRENOM_USER_CONNECT { get; set; }

    public int CLE_USER_SE { get; set; }

    public string NOM_USER_SE { get; set; }

    public string PRENOM_USER_SE { get; set; }

    public string ZONE_SE { get; set; }

    public string TYPE_OBJ_SE { get; set; }

    public Nullable<int> CLE_OBJ_SE { get; set; }

    public string RESULT_SE { get; set; }

    public string COMM_SE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
