
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_IMG
{

    public int CLE_IMG { get; set; }

    public string CODE_IMG { get; set; }

    public string CHEM_IMG { get; set; }

    public Nullable<int> TYPE_IMG { get; set; }

    public byte[] BLOB_IMG { get; set; }

    public Nullable<int> LARGEUR_IMG { get; set; }

    public Nullable<int> HAUTEUR_IMG { get; set; }

    public byte[] BLOB_IMG_2 { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
