
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_INDIC_TAUX
{

    public int CLE_INDIC_OBJ { get; set; }

    public Nullable<int> CLE_LISTE_GEN_DENOMINATEUR { get; set; }

    public Nullable<int> CLE_PREFILTRE_DENOMINATEUR { get; set; }

    public string COULEUR_NOMINATEUR { get; set; }

    public string COULEUR_DENOMINATEUR { get; set; }

    public Nullable<decimal> VAL_MIN { get; set; }

    public Nullable<decimal> VAL_MAX { get; set; }

    public string COULEUR { get; set; }

    public string CHEMIMG { get; set; }

    public string COMPTER_DENOMINATEUR { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
