
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_INVENTAIRE
{

    public int CLE_INVENTAIRE { get; set; }

    public string CODE_INV { get; set; }

    public string NOM_INV { get; set; }

    public string COMM { get; set; }

    public Nullable<int> CLE_DEMANDEUR { get; set; }

    public Nullable<int> CLE_RESPONSABLE { get; set; }

    public Nullable<int> CLE_VISA { get; set; }

    public Nullable<int> CLE_ETAT { get; set; }

    public Nullable<System.DateTime> DATE_DEBUT { get; set; }

    public Nullable<System.DateTime> DATE_FIN { get; set; }

    public string CLOTURER { get; set; }

    public Nullable<int> CLE_TYPE { get; set; }

    public Nullable<int> CLE_MODE { get; set; }

    public Nullable<int> CLE_DECLENCHEUR { get; set; }

    public Nullable<int> NB_PIECES { get; set; }

    public Nullable<decimal> VALEUR_STOCK { get; set; }

    public Nullable<int> NB_SESSION_RDM { get; set; }

    public Nullable<int> NB_PIECE_RDM { get; set; }

    public string ARCHIVE_ { get; set; }

    public string MODELE { get; set; }

    public Nullable<int> SEUIL { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
