
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_INTERV
{

    public int NUM_INTERV { get; set; }

    public string NOM_INTERV { get; set; }

    public string PRENOM_INTERV { get; set; }

    public Nullable<decimal> COUT_HORAIRE { get; set; }

    public Nullable<int> CLE_FAMILLE_INTERV { get; set; }

    public Nullable<int> CLE_CAL_PERS1 { get; set; }

    public Nullable<int> CLE_CAL_PERS_2 { get; set; }

    public string ADRESSE_INTERV { get; set; }

    public string CP_INTERV { get; set; }

    public string VILLE_INTERV { get; set; }

    public string TEL1_INTERV { get; set; }

    public string TEL2_INTERV { get; set; }

    public string E_MAIL_INTERV { get; set; }

    public string COMM { get; set; }

    public string FASS { get; set; }

    public string STR_DATE_NAISS { get; set; }

    public Nullable<int> CLE_MONNAIE { get; set; }

    public Nullable<decimal> COUT_HORAIRE_NUIT { get; set; }

    public Nullable<int> CLE_SPECIALITE { get; set; }

    public string ARCHIVE_ { get; set; }

    public Nullable<int> INT_VIERGE_1 { get; set; }

    public Nullable<int> INT_VIERGE_2 { get; set; }

    public string STR_32_VIERGE { get; set; }

    public string BOOL_VIERGE_1 { get; set; }

    public Nullable<decimal> NUM_VIERGE_1 { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE { get; set; }

    public Nullable<int> CLE_COEFF_F_INTERV { get; set; }

    public Nullable<decimal> COEFF { get; set; }

    public Nullable<int> CLE_COMPTE_ACHAT { get; set; }

    public Nullable<int> CLE_COMPTE_VENTE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public Nullable<int> CLE_VILLE { get; set; }

    public Nullable<int> CLE_REGION { get; set; }

    public Nullable<decimal> X { get; set; }

    public Nullable<decimal> Y { get; set; }

    public Nullable<decimal> Z { get; set; }

    public Nullable<int> CLE_CENTRE_PROFIT { get; set; }

    public string EST_GENERIQUE { get; set; }

    public Nullable<int> NB_INTERVENTION_MAX { get; set; }

    public Nullable<int> CLE_TVA { get; set; }

}

}
