
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_ITEM_GAMME2
{

    public int CLE_ITEM_GAMME2 { get; set; }

    public string CODE { get; set; }

    public string TITRE { get; set; }

    public int TYPE_GAMME { get; set; }

    public Nullable<decimal> DUREE_PREVUE { get; set; }

    public string DESC_ITEM { get; set; }

    public string CHEM_LOGO { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
