
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_LGDIS
{

    public int NUM_ENR { get; set; }

    public string NOM { get; set; }

    public string FICHE { get; set; }

    public string MODIF { get; set; }

    public string INT_FR { get; set; }

    public string INT_GB { get; set; }

    public string INT_ESP { get; set; }

    public string INT_POR { get; set; }

    public string INT_POL { get; set; }

    public string INT_L7 { get; set; }

    public string INT_L8 { get; set; }

    public string INT_L9 { get; set; }

    public string INT_L10 { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
