
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_LIGNE_FACT
{

    public int NUM_LIGNE_FACT { get; set; }

    public Nullable<int> CLE_FACT { get; set; }

    public Nullable<int> CLE_UI { get; set; }

    public Nullable<int> CLE_BT { get; set; }

    public Nullable<int> CLE_LIGNE_BT { get; set; }

    public string NOM { get; set; }

    public Nullable<decimal> QTE { get; set; }

    public Nullable<decimal> COUT_U_HT { get; set; }

    public Nullable<decimal> COUT_TOTAL_HT { get; set; }

    public string A_FACTURER { get; set; }

    public Nullable<int> CAT_VEH { get; set; }

    public string ETAT { get; set; }

    public Nullable<int> CLE_TYPE_TRAV { get; set; }

    public Nullable<int> INT_1 { get; set; }

    public Nullable<int> INT_2 { get; set; }

    public string BOOL_1 { get; set; }

    public Nullable<decimal> NUMERIC_1 { get; set; }

    public Nullable<System.DateTime> DATE_1 { get; set; }

    public string STR_32 { get; set; }

    public Nullable<decimal> QTE_FACTUREE { get; set; }

    public Nullable<decimal> MONTANT_FACTURE { get; set; }

    public Nullable<int> CLE_MONNAIE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
