
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_LIGNE_DOP
{

    public int CLE_LIGNE_DOP { get; set; }

    public int CLE_DOP { get; set; }

    public Nullable<int> CLE_LIGNE_DA { get; set; }

    public string TITRE { get; set; }

    public Nullable<decimal> QTE { get; set; }

    public Nullable<int> CLE_UNITE_CMDE { get; set; }

    public string COMM_LIGNE_DOP { get; set; }

    public string ARCHIVE_ { get; set; }

    public Nullable<int> CLE_MAGASIN { get; set; }

    public Nullable<int> CLE_BUDGET { get; set; }

    public Nullable<int> CLE_CC { get; set; }

    public Nullable<int> CLE_UI { get; set; }

    public Nullable<int> CLE_BT { get; set; }

    public Nullable<System.DateTime> DATE_LIGNE { get; set; }

    public Nullable<int> CLE_DEMANDEUR { get; set; }

    public Nullable<int> CLE_SERVICE { get; set; }

    public Nullable<int> CLE_ORIGINE { get; set; }

    public Nullable<int> DELAI_MAX { get; set; }

    public Nullable<int> DELAI_MIN { get; set; }

    public Nullable<int> CLE_TVA { get; set; }

    public Nullable<int> CLE_USER_CREA { get; set; }

    public Nullable<System.DateTime> DATE_CREA { get; set; }

    public Nullable<int> CLE_USER_LAST_MODIF { get; set; }

    public Nullable<System.DateTime> DATE_LAST_MODIF { get; set; }

    public Nullable<int> INDICE { get; set; }

    public Nullable<decimal> RATIO_UNITE_STOCK { get; set; }

    public Nullable<int> CLE_FOURN { get; set; }

    public string COMM2 { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string REF_CONSTRUCTEUR { get; set; }

    public string CARACTERISTIQUES { get; set; }

    public string DESIGNATION_CMDE { get; set; }

    public string NUM_LDOP_AN { get; set; }

    public string FLAG_EXPORTE { get; set; }

    public Nullable<int> CLE_LIBRE_HA_MAG { get; set; }

    public Nullable<int> CLE_LIBRE_HA1 { get; set; }

}

}
