
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_LIEN_IP_BPU
{

    public int LIEN_IP { get; set; }

    public int LIEN_BPU { get; set; }

    public Nullable<decimal> QTE { get; set; }

    public Nullable<decimal> TEMPS_ALLOUE { get; set; }

    public Nullable<decimal> TEMPS_FACTURE { get; set; }

    public Nullable<decimal> COUT_FACTURE { get; set; }

    public string COMM { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
