
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_LIEN_BT_GAMME
{

    public int LIEN_BT { get; set; }

    public int LIEN_GAMME { get; set; }

    public Nullable<int> INDICE { get; set; }

    public Nullable<int> LIEN_LIGNE_BT { get; set; }

    public string TERMINE { get; set; }

    public Nullable<decimal> TPS { get; set; }

    public string STR_32 { get; set; }

    public string STR_128 { get; set; }

    public Nullable<int> INT_1 { get; set; }

    public string COMM_BT { get; set; }

    public Nullable<decimal> VAL { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
