
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_LIGNE_BL
{

    public int CLE_LIGNE_BL { get; set; }

    public int CLE_BL { get; set; }

    public Nullable<int> CLE_LIGNE_CMDE { get; set; }

    public string TITRE { get; set; }

    public Nullable<decimal> QTE { get; set; }

    public Nullable<System.DateTime> DATE_LIGNE_BL { get; set; }

    public string COMM_LIGNE_BL { get; set; }

    public Nullable<int> CLE_INTERV { get; set; }

    public Nullable<int> CLE_BT { get; set; }

    public Nullable<int> CLE_UI { get; set; }

    public Nullable<int> CLE_CC { get; set; }

    public Nullable<int> CLE_BUDGET { get; set; }

    public Nullable<int> CLE_MAG { get; set; }

    public Nullable<int> CLE_UNITE_CMDE { get; set; }

    public Nullable<int> CLE_VISA_1 { get; set; }

    public Nullable<int> CLE_ETAT_BL { get; set; }

    public Nullable<int> DELAI { get; set; }

    public Nullable<int> CLE_FOURN { get; set; }

    public Nullable<int> CLE_DEFAUT_LIGNE_BL { get; set; }

    public Nullable<int> CLE_DEMANDEUR { get; set; }

    public Nullable<int> CLE_SERVICE { get; set; }

    public Nullable<int> CLE_ORIGINE { get; set; }

    public Nullable<int> DELAI_MIN { get; set; }

    public Nullable<int> CLE_TVA { get; set; }

    public Nullable<int> CLE_USER_CREA { get; set; }

    public Nullable<System.DateTime> DATE_CREA { get; set; }

    public Nullable<int> CLE_USER_LAST_MODIF { get; set; }

    public Nullable<System.DateTime> DATE_LAST_MODIF { get; set; }

    public Nullable<int> INDICE { get; set; }

    public Nullable<decimal> RATIO_UNITE_STOCK { get; set; }

    public Nullable<decimal> COUTS_FRAIS_HT { get; set; }

    public Nullable<decimal> COUTS_FRAIS_TTC { get; set; }

    public string COMM2 { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string BLOC_PAIE { get; set; }

    public string NUM_LBL_AN { get; set; }

    public string FLAG_EXPORTE { get; set; }

    public Nullable<int> CLE_LIBRE_HA_MAG { get; set; }

    public Nullable<int> CLE_LIBRE_HA1 { get; set; }

    public string NUMERO_FACTURE { get; set; }

    public Nullable<System.DateTime> DATE_FACTURE { get; set; }

    public Nullable<decimal> MONTANT_FACTURE { get; set; }

    public Nullable<int> CLE_ETAT_FACTURATION { get; set; }

}

}
