
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_LIEN_EXPORT_CHAMPS
{

    public int CLE_LIEN_EXPORT_CHAMP { get; set; }

    public Nullable<int> CLE_LIEN_EXPORT { get; set; }

    public Nullable<int> CLE_LIEN_CHAMP { get; set; }

    public Nullable<int> CLE_LIEN_IMPORTANCE { get; set; }

    public string NOM_ALIAS { get; set; }

    public Nullable<int> LIEN_CHAMP_JOINTURE { get; set; }

    public string OBLIGATOIRE { get; set; }

    public string VISIBLE { get; set; }

    public string CLAUSE_SPECIALE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
