
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_LIGNE_FACT_CMDE
{

    public int CLE_LIGNE_FACT_CMDE { get; set; }

    public int CLE_FACT_CMDE { get; set; }

    public Nullable<int> CLE_LIGNE_CMDE { get; set; }

    public Nullable<int> CLE_LIGNE_BL { get; set; }

    public string TITRE { get; set; }

    public Nullable<decimal> QTE { get; set; }

    public Nullable<System.DateTime> DATE_LIGNE_FACT_CMDE { get; set; }

    public string COMM_LIGNE_FACT_CMDE { get; set; }

    public Nullable<int> CLE_INTERV { get; set; }

    public Nullable<int> CLE_BUDGET { get; set; }

    public string CODE_FACT { get; set; }

    public Nullable<int> INDICE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
