
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_LIEN_USER_INDIC_TAUX
{

    public int CLE_LIEN_USER_INDIC_OBJ { get; set; }

    public Nullable<int> CLE_TYPE_REPR_INDIC { get; set; }

    public string AFFICHER_REPR { get; set; }

    public string AFFICHER_CAMEMBERT { get; set; }

    public Nullable<int> CODE_POSITION { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
