
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_LIGNE_TAXE
{

    public int CLE_LIGNE_TAXE { get; set; }

    public int CLE_TVA { get; set; }

    public string NOM { get; set; }

    public string COMM { get; set; }

    public Nullable<decimal> POURC_CIBLE { get; set; }

    public Nullable<decimal> POURC_APPL { get; set; }

    public Nullable<int> TYPE_CIBLE { get; set; }

    public Nullable<int> INDICE { get; set; }

    public Nullable<int> COLONE_CIBLE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
