
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_LIBELLES_CR
{

    public int NUM { get; set; }

    public string CODE { get; set; }

    public string NOM_FR { get; set; }

    public string NOM_GB { get; set; }

    public string NOM_ESP { get; set; }

    public string NOM_POR { get; set; }

    public string NOM_POL { get; set; }

    public string NOM_7 { get; set; }

    public string NOM_8 { get; set; }

    public string NOM_9 { get; set; }

    public string NOM_10 { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
