
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_LIEN_DI_JH_INTERV_PREFERE
{

    public int CLE_LIEN_DI_JH_INTERV_PREFERE { get; set; }

    public int CLE_DI { get; set; }

    public int CLE_JOUR { get; set; }

    public string JOUR_PREFERE { get; set; }

    public Nullable<int> H_DEB_PLAGE1 { get; set; }

    public Nullable<int> H_FIN_PLAGE1 { get; set; }

    public Nullable<int> H_DEB_PLAGE2 { get; set; }

    public Nullable<int> H_FIN_PLAGE2 { get; set; }

    public string COMM { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
