
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_LIGNE_IP
{

    public int NUM_LIGNE_IP { get; set; }

    public string TYPE_LIGNE_IP { get; set; }

    public Nullable<int> CLE_ELEMENT { get; set; }

    public Nullable<decimal> QTE { get; set; }

    public Nullable<decimal> COUT_LIGNE_IP { get; set; }

    public Nullable<int> CLE_IP { get; set; }

    public Nullable<int> INT_VIERGE { get; set; }

    public Nullable<decimal> NUM_VIERGE { get; set; }

    public string BOOL_VIERGE { get; set; }

    public Nullable<System.DateTime> ST32_VIERGE { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE { get; set; }

    public Nullable<decimal> COEFF { get; set; }

    public Nullable<decimal> COUT_2_LIGNE_IP { get; set; }

    public Nullable<decimal> TOTAL_COUT_2_LIGNE_IP { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public Nullable<int> CLE_BPU { get; set; }

}

}
