
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_LOT
{

    public int CLE_LOT { get; set; }

    public int CLE_PIECE { get; set; }

    public int CLE_MAGASIN { get; set; }

    public int CLE_STOCK { get; set; }

    public int NUM_LOT { get; set; }

    public string CODE_LOT { get; set; }

    public string COMM_LOT { get; set; }

    public Nullable<System.DateTime> DATE_CREATION { get; set; }

    public Nullable<decimal> QTE_INITIALE { get; set; }

    public Nullable<decimal> QTE { get; set; }

    public string NUM_LOT_EXTERNE { get; set; }

    public string ARCHIVE_ { get; set; }

    public Nullable<decimal> COUT_U { get; set; }

    public Nullable<System.DateTime> DATE_PEREMPTION_LOT { get; set; }

    public Nullable<decimal> COUT_LOT { get; set; }

    public Nullable<decimal> COUT_FRAIS_LOT { get; set; }

    public Nullable<decimal> COUT_TOTAL { get; set; }

    public Nullable<decimal> COUT_U_AVEC_FRAIS { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
