
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_MAGASIN
{

    public int NUM_MAGASIN { get; set; }

    public string DES_MAGASIN { get; set; }

    public Nullable<int> CLE_LIEU { get; set; }

    public string ADR_LIVR { get; set; }

    public string CP_LIVR { get; set; }

    public string VILLE_LIVR { get; set; }

    public string TEL_LIVR { get; set; }

    public string FAX_LIVR { get; set; }

    public string ADR_FACT { get; set; }

    public string CP_FACT { get; set; }

    public string VILLE_FACT { get; set; }

    public string TEL_FACT { get; set; }

    public string FAX_FACT { get; set; }

    public string NOM_LIVR { get; set; }

    public string NOM_FACT { get; set; }

    public Nullable<int> INT_VIERGE_1 { get; set; }

    public Nullable<int> INT_VIERGE_2 { get; set; }

    public string STR32_VIERGE_1 { get; set; }

    public string STR32_VIERGE_2 { get; set; }

    public string BOOL_VIERGE_1 { get; set; }

    public string BOOL_VIERGE_2 { get; set; }

    public Nullable<decimal> NUM_VIERGE { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE { get; set; }

    public string PAYS_FACT { get; set; }

    public string PAYS_LIVR { get; set; }

    public string COMM { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string CHEM_LOGO_RPT { get; set; }

    public Nullable<int> CLE_CC { get; set; }

    public byte[] LOGO_RPT { get; set; }

}

}
