
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_MODIF
{

    public int CLE_MODIF { get; set; }

    public string NOM_BASE { get; set; }

    public string DATE_MODIF { get; set; }

    public Nullable<int> S { get; set; }

    public Nullable<int> MS { get; set; }

    public Nullable<int> TYPE_MODIF { get; set; }

    public string NOM_TABLE { get; set; }

    public string NOM_CHAMP_CLE { get; set; }

    public Nullable<int> CLE_ENREG { get; set; }

    public Nullable<System.DateTime> DATE_MODIF2 { get; set; }

    public Nullable<int> INT_1 { get; set; }

    public string STR_32_1 { get; set; }

    public Nullable<decimal> NUM_1 { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
