
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_NOMENC_MATRICULE
{

    public int CLE_NOMENC_MATRICULE { get; set; }

    public Nullable<int> CLE_UI { get; set; }

    public Nullable<decimal> QTE { get; set; }

    public Nullable<int> CLE_PIECE { get; set; }

    public string TEXT_ { get; set; }

    public string PLAN_NOMENC { get; set; }

    public string REPERE_NOMENC { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
