
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_NOMENC
{

    public int NUM_LIGNE { get; set; }

    public Nullable<int> NUM_UI { get; set; }

    public decimal QTE { get; set; }

    public Nullable<int> NUM_PIECE { get; set; }

    public Nullable<int> INT_VIERGE_1 { get; set; }

    public string STR32_VIERGE { get; set; }

    public string BOOL_VIERGE { get; set; }

    public Nullable<int> INT_VIERGE_2 { get; set; }

    public Nullable<decimal> NUM_VIERGE { get; set; }

    public string TEXT_ { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string PLAN_NOMENC { get; set; }

    public string REPERE_NOMENC { get; set; }

    public Nullable<System.DateTime> DATE_FIN_GARANTIE { get; set; }

    public Nullable<int> NUM_MAGASIN { get; set; }

}

}
