
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_PARAMS_ARIBA
{

    public int CLE_PARAM_ARIBA { get; set; }

    public string CHEMIN_FICHIER_EXP_LGCO { get; set; }

    public string NOM_FICHIER_EXP_LGCO { get; set; }

    public string CHEMIN_FICHIER_LOG_EXP_LGCO { get; set; }

    public string NOM_FICHIER_LOG_EXP_LGCO { get; set; }

    public string CHEMIN_FICHIER_EXP_RECEPT { get; set; }

    public string NOM_FICHIER_EXP_RECEPT { get; set; }

    public string CHEMIN_FICHIER_LOG_EXP_RECEPT { get; set; }

    public string NOM_FICHIER_LOG_EXP_RECEPT { get; set; }

    public string CHEMIN_FICHIER_IMP_LGCO { get; set; }

    public string NOM_FICHIER_IMP_LGCO { get; set; }

    public string CHEMIN_FICHIER_LOG_IMP_LGCO { get; set; }

    public string NOM_FICHIER_LOG_IMP_LGCO { get; set; }

    public string CHEMIN_FICHIER_OLD_IMP_LGCO { get; set; }

    public string HORODATAGE_EXP { get; set; }

    public string HOST_FTP { get; set; }

    public string PASS_FTP { get; set; }

    public string UID_FTP { get; set; }

    public string PORT_FTP { get; set; }

    public string MODE_FTP_PASSIF { get; set; }

    public Nullable<int> CLE_ETAT_CIBLE_LGCO_EXP { get; set; }

    public Nullable<int> CLE_ETAT_CIBLE_LGCO_AFTEREXP { get; set; }

    public Nullable<int> CLE_ETAT_CIBLE_VALIDE_LGCO_IMP { get; set; }

    public Nullable<int> CLE_ETAT_CIBLE_ANNUL_LGCO_IMP { get; set; }

    public string MAIL_SI_KO { get; set; }

    public Nullable<int> LISTE_DESTINATAIRE_MAIL { get; set; }

    public string USE_FTP { get; set; }

    public string CHEMIN_FICHIER_ERR_IMP_LGCO { get; set; }

    public Nullable<int> CLE_ETAT_CIBLE_ERREUR_LGCO_IMP { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
