
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_PARAMS_AUDROS
{

    public int CLE_PARAMS_AUDROS { get; set; }

    public string SERVER_AUDROS { get; set; }

    public string USER_ADMIN_AUDROS { get; set; }

    public string PASS_ADMIN_AUDROS { get; set; }

    public string GROUP_ADMIN_AUDROS { get; set; }

    public string LEVEL_ADMIN_AUDROS { get; set; }

    public string GROUP_AUTRE_AUDROS { get; set; }

    public string LEVEL_AUTRE_AUDROS { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
