
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_PARAMS_LDAP
{

    public int CLE_PARAM_LDAP { get; set; }

    public string ACTIVE_LDAP { get; set; }

    public string HOTE { get; set; }

    public Nullable<int> PORT { get; set; }

    public string RADICAL_DOM { get; set; }

    public string CONTROL_LDAP_STRICT { get; set; }

    public string CONTROL_MIXTE { get; set; }

    public string BASE_DN { get; set; }

    public string NOM_USER { get; set; }

    public string PW { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
