
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_PARAMS_APPS
{

    public int CLE_PARAMS_APPS { get; set; }

    public Nullable<int> CLE_ETAT_BT_ACCEPTED { get; set; }

    public string LABEL_ETAT_BT_ACCEPTED { get; set; }

    public Nullable<int> CLE_ETAT_BT_UPDATE_DI { get; set; }

    public Nullable<int> CLE_ETAT_DI_UPDATED { get; set; }

    public string NOTIF_TO_DEMANDEUR_DI { get; set; }

    public Nullable<int> CLE_ETAT_BT_NOTIF_DEMANDEUR { get; set; }

    public string NOTIF_TO_TECHNICIEN_BT { get; set; }

    public Nullable<int> NB_MAX_DI_LISTE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
