
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_PARAMS_COMPTE_USER
{

    public int CLE_PARAMS_COMPTE_USER { get; set; }

    public Nullable<int> SE_CONNEXION_MAX { get; set; }

    public Nullable<int> MDP_CONNEXION_MAX { get; set; }

    public Nullable<int> SE_LONGEUR_MIN { get; set; }

    public Nullable<int> MDP_LONGEUR_MIN { get; set; }

    public Nullable<int> SE_CHIFFRE_MIN { get; set; }

    public Nullable<int> MDP_CHIFFRE_MIN { get; set; }

    public Nullable<int> SE_MAJUSCULE_MIN { get; set; }

    public Nullable<int> MDP_MAJUSCULE_MIN { get; set; }

    public Nullable<int> SE_CARAC_SPE_MIN { get; set; }

    public Nullable<int> MDP_CARAC_SPE_MIN { get; set; }

    public Nullable<int> MDP_AVERT_EXPIRATION { get; set; }

    public Nullable<int> SE_INTERDIRE_DERNIERS { get; set; }

    public Nullable<int> MDP_INTERDIRE_DERNIERS { get; set; }

    public string MDP_AVERTIR { get; set; }

    public string MDP_INTERDIR { get; set; }

    public string MDP_BLOCAGE { get; set; }

    public string SE_BLOCAGE { get; set; }

    public string BLOQUER_SUPERVISEUR { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
