
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_PARAMS_X3
{

    public int CLE_PARAMS_X3 { get; set; }

    public Nullable<int> CLE_ETAT_CMD_EXPORT { get; set; }

    public string X3V2 { get; set; }

    public string CHEMIN_REP_EXPORT_X3V2 { get; set; }

    public string RADICAL_FICHIER_EXP_X3V2 { get; set; }

    public string CHEMIN_LOG_X3V2 { get; set; }

    public string RADICAL_REEXPORT { get; set; }

    public string RADICAL_RECEPTION { get; set; }

    public string CHEMIN_REP_IMPORT { get; set; }

    public string RADICAL_IMPORT_FEED_LIGNE { get; set; }

    public string REPERTOIRE_ARCHIVE { get; set; }

    public string MAIL_LOG_KO { get; set; }

    public string DEST_MAIL { get; set; }

    public string EXPORT_LC_PASSE_EXP { get; set; }

    public string FEEDLC_PASSE_FACT { get; set; }

    public string RADICAL_FEEDFACT { get; set; }

    public Nullable<int> TYPE_REPARTITION_FRAIS_AUTO { get; set; }

    public string RADICAL_PRESTATION { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
