
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_PARAMS_AX
{

    public int CLE_PARAMS_AX { get; set; }

    public Nullable<int> NUM_ETAT_CMDE_A_EXPORTER { get; set; }

    public Nullable<int> NUM_ETAT_CMDE_EXPORTE { get; set; }

    public Nullable<int> NUM_GROUPE_DEST_MAIL { get; set; }

    public string MAIL_ACTIVE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
