
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_PARAMS_CMDE
{

    public int CLE_PARAMS_CMDE { get; set; }

    public string GESTION_FRAIS_LIGNE { get; set; }

    public string MODIFY_PENDING { get; set; }

    public string GESTION_IMPUTATION { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string ETAT_PREPA_CMDE { get; set; }

    public string DEVIS_CANT_MODIFY { get; set; }

    public string DEMANDEUR_OBLIGATOIRE { get; set; }

    public string CC_OBLIGATOIRE { get; set; }

    public string UTILISER_MAIL_INTERLOC_PPAL { get; set; }

    public string BL_DATEBL_OBLIGATOIRE { get; set; }

    public string GEN_AUTO_CMDE_MAG_USER { get; set; }

    public string CACHER_TVA_RECEPTION { get; set; }

}

}
