
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_PARAMS_LISTES_GEN
{

    public int CLE_LISTES_GEN { get; set; }

    public string LISTE_BT { get; set; }

    public string LISTE_UI { get; set; }

    public string LISTE_DI { get; set; }

    public string LISTE_IP { get; set; }

    public string LISTE_MVT { get; set; }

    public string LISTE_PIECE { get; set; }

    public string LISTE_STOCK { get; set; }

    public string LISTE_MAT { get; set; }

    public string LISTE_PNEU { get; set; }

    public string LISTE_FOURN { get; set; }

    public string LISTE_INTERV { get; set; }

    public string LISTE_CLIENT { get; set; }

    public string LISTE_DEVIS_F { get; set; }

    public string LISTE_FACTURE_F { get; set; }

    public string LISTE_DS { get; set; }

    public string LISTE_BS { get; set; }

    public string LISTE_BR { get; set; }

    public string LISTE_CMDE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string ACTIV_LISTES_GEN { get; set; }

    public string EXPORT_DONNEES_BRUT { get; set; }

}

}
