
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_PARAMS_ACHAT
{

    public int CLE_PARAMS_ACHAT { get; set; }

    public string VISAS_IN_WF_DEVIS { get; set; }

    public string VISAS_IN_WF_CMDE { get; set; }

    public string VISA_1_DEVIS_OBLIGATOIRE { get; set; }

    public string VISA_2_DEVIS_OBLIGATOIRE { get; set; }

    public string VISA_1_CMDE_OBLIGATOIRE { get; set; }

    public string VISA_2_CMDE_OBLIGATOIRE { get; set; }

    public Nullable<decimal> MONTANT_VISA_1_DEVIS { get; set; }

    public Nullable<decimal> MONTANT_VISA_2_DEVIS { get; set; }

    public Nullable<decimal> MONTANT_VISA_1_CMDE { get; set; }

    public Nullable<decimal> MONTANT_VISA_2_CMDE { get; set; }

    public Nullable<int> CLE_VISEUR_1_DEF_DEVIS { get; set; }

    public Nullable<int> CLE_VISEUR_2_DEF_DEVIS { get; set; }

    public Nullable<int> CLE_VISEUR_1_DEF_CMDE { get; set; }

    public Nullable<int> CLE_VISEUR_2_DEF_CMDE { get; set; }

    public string BLOQUER_LCMDE_FROM_LDEVIS { get; set; }

    public string FUSIONNER_DEVIS_CREE_CMDE { get; set; }

    public string CONTRAINTES_RGP { get; set; }

    public string DATE_VALIDITE_BLOQUANTE { get; set; }

    public string ACCEPT_DEVIS_AUTO { get; set; }

    public string MESSAGE_SI_PAS_1ERE_IMP { get; set; }

    public string CHOISIR_FASS_TO_SEND { get; set; }

    public string MODIFY_PENDING { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public Nullable<int> TYPE_VISEUR { get; set; }

    public string VISEUR_FONCTION_MONTANT { get; set; }

    public string VISA_DEVIS_OBLIGATOIRE { get; set; }

    public string VISA_CMDE_OBLIGATOIRE { get; set; }

    public string NO_MODIF_VISEUR { get; set; }

    public string PIECE_GENERIQUE { get; set; }

    public string COMM_OBLIG_PIECE_GEN { get; set; }

    public string GESTION_VALIDATION_DA { get; set; }

    public string GESTION_ANNULATION_DA { get; set; }

    public string BLOQUER_RGP_SI_DA_DIFF { get; set; }

    public string GESTION_ANNULATION_DEVIS { get; set; }

    public string NO_MODIF_FRAIS_CMDE_ISSU_DEVIS { get; set; }

    public string MAIL_LORS_DA_TRANSMISE { get; set; }

    public Nullable<int> CLE_GPE_DEST_DA_TRANSMISE { get; set; }

    public string MAIL_LORS_DA_VALIDEE { get; set; }

    public Nullable<int> CLE_GPE_DEST_DA_VALIDE { get; set; }

    public string MAIL_LORS_DOP_TCO { get; set; }

    public Nullable<int> CLE_GPE_DEST_DOP_TCO { get; set; }

    public string MAIL_LORS_DEVIS_AVALIDER { get; set; }

    public Nullable<int> CLE_GPE_DEST_DEVIS_AVALIDER { get; set; }

    public string MAIL_LORS_DEVIS_ACCEPTE { get; set; }

    public Nullable<int> CLE_GPE_DEST_DEVIS_ACCEPTE { get; set; }

    public string FRAISCMDE_NOIMPACT_COUTCMDE { get; set; }

    public string MAIL_LORS_DA_ANNULEE { get; set; }

    public Nullable<int> CLE_GPE_DEST_DA_ANNULEE { get; set; }

    public string MAIL_LORS_DEVIS_ANNULE { get; set; }

    public Nullable<int> CLE_GPE_DEST_DEVIS_ANNULE { get; set; }

    public string MAIL_LORS_CMDE_EAV { get; set; }

    public string MAIL_GPE_DEST_CMDE { get; set; }

    public Nullable<int> CLE_GPE_DEST_CMDE { get; set; }

    public string AJT_DEMANDEUR_AUX_DEST_MAILS { get; set; }

    public string AJT_ORIGINE_AUX_DEST_MAILS { get; set; }

    public string MONTANT_DEVISE_TO_MONTANT_REF { get; set; }

    public string INFOS_FACTURATION { get; set; }

}

}
