
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_POUVOIR
{

    public int CLE_POUVOIR { get; set; }

    public Nullable<int> CLE_DONNEUR { get; set; }

    public Nullable<int> CLE_RECEVEUR { get; set; }

    public Nullable<System.DateTime> DATE_DEBUT { get; set; }

    public Nullable<System.DateTime> DATE_FIN { get; set; }

    public string ARCHIVE_ { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
