
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_PROFILE
{

    public int CLE_PROFILE { get; set; }

    public string NOM_PROFILE { get; set; }

    public string VOIR_COUTS_DS_LISTES { get; set; }

    public string STR32_VIERGE { get; set; }

    public Nullable<int> INT_VIERGE { get; set; }

    public Nullable<System.DateTime> DATE_VIERGE { get; set; }

    public string BOOL_VIERGE { get; set; }

    public string NE_PAS_VOIR_COUTS_INTERV { get; set; }

    public string NE_PAS_VOIR_COUTS_FOURN { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
