
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_RECEPTION
{

    public int CLE_RECEPTION { get; set; }

    public int CLE_MVT { get; set; }

    public int NUM_LIGNE_CMDE { get; set; }

    public System.DateTime DATE_RECEPTION { get; set; }

    public decimal MONTANT_UNITE_HT { get; set; }

    public decimal QTE { get; set; }

    public decimal MONTANT_TVA { get; set; }

    public decimal MONTANT_FACTURE { get; set; }

    public string COMM { get; set; }

    public string CODE_BL { get; set; }

    public Nullable<decimal> TAUX_TVA { get; set; }

    public Nullable<int> CLE_TVA { get; set; }

    public string CODE_FACTURE { get; set; }

    public Nullable<System.DateTime> DATE_FACTURE { get; set; }

    public string EXPORTE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public Nullable<int> CLE_USER { get; set; }

    public Nullable<System.DateTime> DATE_BL { get; set; }

}

}
