
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_REGLE_DI_TO_BT
{

    public int NUM_REGLE { get; set; }

    public string TYPE_TRAV { get; set; }

    public string NOM_DEM { get; set; }

    public string FAMILLE_EQ { get; set; }

    public string HORAIRE { get; set; }

    public Nullable<System.DateTime> DATE_H_DEB { get; set; }

    public Nullable<System.DateTime> DATE_H_FIN { get; set; }

    public string NOM_INTERV { get; set; }

    public string PRENOM_INTERV { get; set; }

    public Nullable<int> CLE_INTERV { get; set; }

    public Nullable<int> CLE_DEM { get; set; }

    public Nullable<int> CLE_FAM { get; set; }

    public Nullable<int> CLE_TT { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
