
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_RETOUR_SMS
{

    public int CLE_RETOUR_SMS { get; set; }

    public Nullable<int> CLE_HISTO_SMS { get; set; }

    public Nullable<System.DateTime> DATE_RECEPTION_SMS { get; set; }

    public string MESS_RETOUR_SMS { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string RETOUR_OK { get; set; }

    public string MESSAGE_ERREUR { get; set; }

    public Nullable<int> CLE_ELEMENT { get; set; }

}

}
