
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_SESSION_HABILITATION
{

    public int CLE_SESSION_HABILITATION { get; set; }

    public string NOM_SESSION_HABILITATION { get; set; }

    public Nullable<int> CLE_HAB { get; set; }

    public Nullable<int> CLE_FOURN { get; set; }

    public Nullable<System.DateTime> DATE_DEB_PREVU { get; set; }

    public Nullable<System.DateTime> DATE_FIN_PREVU { get; set; }

    public Nullable<System.DateTime> DATE_DEB_REEL { get; set; }

    public Nullable<System.DateTime> DATE_FIN_REEL { get; set; }

    public string ADR { get; set; }

    public string ADR2 { get; set; }

    public string ADR3 { get; set; }

    public string CP { get; set; }

    public Nullable<int> CLE_VILLE { get; set; }

    public Nullable<int> CLE_REGION { get; set; }

    public string PAYS { get; set; }

    public string COMM { get; set; }

    public string FASS { get; set; }

    public Nullable<System.DateTime> DATE_DEBUT_HAB { get; set; }

    public Nullable<int> CLE_CMDE { get; set; }

    public string TERMINE { get; set; }

    public string ARCHIVE_ { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
