
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_SITE
{

    public int CLE_SITE { get; set; }

    public string NOM_SITE { get; set; }

    public string SIRET { get; set; }

    public string TVA_IC { get; set; }

    public Nullable<int> CLE_RS_SITE { get; set; }

    public string ADRESSE_SITE { get; set; }

    public string CP_SITE { get; set; }

    public string VILLE_SITE { get; set; }

    public string PAYS_SITE { get; set; }

    public string TEL_SITE { get; set; }

    public string FAX_SITE { get; set; }

    public Nullable<int> CLE_RS_SITE_LIVR { get; set; }

    public string ADRESSE_SITE_LIVR { get; set; }

    public string CP_SITE_LIVR { get; set; }

    public string VILLE_SITE_LIVR { get; set; }

    public string PAYS_SITE_LIVR { get; set; }

    public string TEL_SITE_LIVR { get; set; }

    public string FAX_SITE_LIVR { get; set; }

    public Nullable<int> CLE_RS_SITE_FACT { get; set; }

    public string ADRESSE_SITE_FACT { get; set; }

    public string CP_SITE_FACT { get; set; }

    public string VILLE_SITE_FACT { get; set; }

    public string PAYS_SITE_FACT { get; set; }

    public string TEL_SITE_FACT { get; set; }

    public string FAX_SITE_FACT { get; set; }

    public int CLE_MAGASIN_DEF { get; set; }

    public string VOIR_MAG_INTERDITS { get; set; }

    public string VOIR_DATA_INTERDITE { get; set; }

    public Nullable<System.DateTime> DATE_CREATION { get; set; }

    public string NOM_SIEGE { get; set; }

    public string NOM_LIVR { get; set; }

    public string NOM_FACT { get; set; }

    public string TRAV_BLOQUE_SI_NO_PERS_DU_SITE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public Nullable<int> NIVEAU_EQT_AUTORISES { get; set; }

    public string AUTORISER_ALL_USER { get; set; }

    public string AUTORISER_ALL_INTERV { get; set; }

    public string AUTORISER_ALL_DEM { get; set; }

    public string AUTORISER_ALL_SERVICE { get; set; }

    public string AUTORISER_ALL_UI { get; set; }

    public string AUTORISER_ALL_MAG { get; set; }

    public string AUTORISER_ALL_FOURN { get; set; }

    public string AUTORISER_ALL_CLIENT { get; set; }

    public string AUTORISER_ALL_BUDGET { get; set; }

    public string AUTORISER_ALL_FAM_PCE { get; set; }

    public string AUTORISER_ALL_UTILISATION { get; set; }

    public string AUTORISER_ALL_FAM_UI { get; set; }

    public string AUTORISER_ALL_TYPE_UI { get; set; }

    public string AUTORISER_ALL_CC { get; set; }

    public string AUTORISER_ALL_LIEU { get; set; }

    public string AUTORISER_ALL_TT { get; set; }

    public string AUTORISER_ALL_FAM_TRAV { get; set; }

    public string MODE_INTERDIRE_UI { get; set; }

    public string MODE_AUTORISE_UI { get; set; }

    public Nullable<int> NIVEAU_UI_AUTORISE { get; set; }

    public string VOIR_UI_AFF_FAM_AUTORISER { get; set; }

    public string VOIR_BT_AFF_FAM_TRAV_AUTORISER { get; set; }

    public string VOIR_DI_AFF_FAM_TRAV_AUTORISER { get; set; }

    public string VOIR_BT_AFF_TT_AUTORISER { get; set; }

    public string VOIR_DI_AFF_TT_AUTORISER { get; set; }

    public string EXCLURE_RESTRICTION_UI_SUR_DI { get; set; }

    public string EXCLURE_RESTRICTION_UI_SUR_BT { get; set; }

    public string EXCLURE_RESTRICTION_UI_SUR_IP { get; set; }

}

}
