
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_SOUS_LIGNE_BT
{

    public int CLE_SOUS_LIGNE_BT { get; set; }

    public int CLE_LIGNE_BT { get; set; }

    public Nullable<System.DateTime> DATE_DEB { get; set; }

    public Nullable<System.DateTime> DATE_FIN { get; set; }

    public Nullable<int> CLE_FAMILLE_SOUS_LIGNE_BT { get; set; }

    public string TEXT_ { get; set; }

    public Nullable<decimal> QTE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
