
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_TABLE
{

    public int CLE_TABLE { get; set; }

    public string CODE_TABLE { get; set; }

    public string NOM_TABLE { get; set; }

    public Nullable<int> LIEN_TYPE_TABLE { get; set; }

    public Nullable<int> LIEN_OBJET { get; set; }

    public Nullable<int> LIEN_BASE { get; set; }

    public string STR_128 { get; set; }

    public string COMM { get; set; }

    public string SCRIPT_CREA_TABLE { get; set; }

    public string ENREG_DEF { get; set; }

    public string VAL_DEF { get; set; }

    public Nullable<int> LIEN_TYPE_EXPORT { get; set; }

    public string INUTILISEE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
