
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_TYPE_CHAMP
{

    public int CLE_TYPE_CHAMP { get; set; }

    public string CODE_TYPE_CHAMP { get; set; }

    public string NOM_TYPE_CHAMP { get; set; }

    public string NBRE_OCTETS { get; set; }

    public string TYPE_STD { get; set; }

    public string COMMENTAIRE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
