
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_TYPE_TRAV
{

    public int NUM_TYPE_TRAV { get; set; }

    public Nullable<int> NIV_TYPE_TRAV { get; set; }

    public string DES_TYPE_TRAV { get; set; }

    public Nullable<int> CLE_IMAGE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string MODE_ACHATS_DIRECTS { get; set; }

}

}
