
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_UI
{

    public int NUM_UI { get; set; }

    public Nullable<int> UI_FILS { get; set; }

    public Nullable<int> CLE_CC { get; set; }

    public Nullable<int> CLE_TUI { get; set; }

    public Nullable<int> CLE_FAM { get; set; }

    public string CODE_UI { get; set; }

    public string DESIGNATION_UI { get; set; }

    public string COM_UI { get; set; }

    public string FASS_UI { get; set; }

    public string PHOTO { get; set; }

    public Nullable<int> CPT_UI1 { get; set; }

    public Nullable<int> CPT_UI2 { get; set; }

    public Nullable<int> CPT_UI3 { get; set; }

    public Nullable<int> CLE_CPT_1 { get; set; }

    public Nullable<int> CLE_CPT_2 { get; set; }

    public Nullable<int> CLE_CPT_3 { get; set; }

    public Nullable<int> CLE_LIEU { get; set; }

    public Nullable<int> UI_FRERE { get; set; }

    public Nullable<int> TYPE_CALENDRIER { get; set; }

    public Nullable<System.DateTime> DATE_MAJ_CPT1 { get; set; }

    public Nullable<System.DateTime> DATE_MAJ_CPT2 { get; set; }

    public Nullable<System.DateTime> DATE_MAJ_CPT3 { get; set; }

    public Nullable<int> TPS_THQ_FCTMT { get; set; }

    public Nullable<decimal> COUT_HORAIRE_IMMO { get; set; }

    public Nullable<int> CLE_LIBRE { get; set; }

    public Nullable<decimal> VIERGE_INT2 { get; set; }

    public string VIERGE_CHAINE_32 { get; set; }

    public string ARCHIVE_ { get; set; }

    public string UI_BOUGEE { get; set; }

    public string EST_MATRICULE { get; set; }

    public string EN_SERVICE { get; set; }

    public string COUT_LAVAGE { get; set; }

    public Nullable<int> CSTE_CPT_1 { get; set; }

    public Nullable<int> CSTE_CPT_2 { get; set; }

    public Nullable<int> CUMUL_CPT_1 { get; set; }

    public Nullable<int> CUMUL_CPT_2 { get; set; }

    public string CODE_SUPERVISION { get; set; }

    public string BOOL_1 { get; set; }

    public string STR_32 { get; set; }

    public Nullable<int> INT_1 { get; set; }

    public Nullable<int> CLE_PERE { get; set; }

    public string SUPPRIMEE { get; set; }

    public Nullable<int> CLE_MATRICULE { get; set; }

    public string EST_PNEU { get; set; }

    public string UI_SOUS_GARANTIE { get; set; }

    public Nullable<System.DateTime> DATE_FIN_GARANTIE { get; set; }

    public Nullable<int> CLE_CLIENT { get; set; }

    public Nullable<int> CLE_ETAT_UI { get; set; }

    public string MATERIAUX_VIGILANCE { get; set; }

    public string EST_VEHICULE { get; set; }

    public Nullable<int> CLE_NIVEAU { get; set; }

    public Nullable<int> CLE_UI_CENTRAL { get; set; }

    public Nullable<decimal> VOLUME_UI_CENTRAL { get; set; }

    public Nullable<decimal> CONCENTRATION_UI_CENTRAL { get; set; }

    public string ALERTE_CAN_CREATE_DI { get; set; }

    public string DESC_ETAT { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public string B_EST_NOEUD { get; set; }

    public Nullable<int> CLE_GROUPE { get; set; }

    public Nullable<int> CLE_ENSEMBLE { get; set; }

    public Nullable<int> CLE_SOUS_ENSEMBLE { get; set; }

    public Nullable<decimal> X { get; set; }

    public Nullable<decimal> Y { get; set; }

    public Nullable<decimal> Z { get; set; }

    public Nullable<decimal> COEFF_ACTUALISE { get; set; }

    public Nullable<decimal> PRIX_ACTUALISE { get; set; }

    public Nullable<System.DateTime> DATE_ACTUALISE { get; set; }

    public Nullable<System.DateTime> DATE_ARCHIVAGE { get; set; }

    public string MOTIF_ARCHIVAGE { get; set; }

    public string LECTURE_SEULE { get; set; }

    public Nullable<int> CLE_LIGNE_PROD { get; set; }

    public Nullable<decimal> NUM_PK { get; set; }

    public string NUM_POTEAU_LAC { get; set; }

    public Nullable<int> CLE_INTERV { get; set; }

    public string EST_UNE_CHAMBRE { get; set; }

    public string EST_OCCUPEE { get; set; }

    public Nullable<int> CLE_OCCUP_CHAMBRE { get; set; }

    public Nullable<int> CLE_ADR_LIVRAISON_CLIENT { get; set; }

    public Nullable<int> CLE_ADR_FACTURATION_CLIENT { get; set; }

    public Nullable<int> NUM_INTERV1 { get; set; }

    public Nullable<int> NUM_INTERV2 { get; set; }

    public Nullable<int> NUM_DEMANDEUR { get; set; }

    public string UI_A_CONSIGNER { get; set; }

    public string DETECT_UIFILS_A_CONSIGNER { get; set; }

    public string UI_EST_CONSIGNER { get; set; }

    public byte[] IMG_QRCODE { get; set; }

}

}
