
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_UI_VOLVO
{

    public int NUM_UI { get; set; }

    public Nullable<System.DateTime> DATE_DEP_CTR { get; set; }

    public Nullable<System.DateTime> DATE_FIN_CTR { get; set; }

    public Nullable<int> DUREE_CTR { get; set; }

    public Nullable<decimal> PRIX_KM { get; set; }

    public int CLE_CC_RESP { get; set; }

    public int CLE_CC_ENTR { get; set; }

    public Nullable<int> KM_CONTRAT { get; set; }

    public Nullable<int> KM_MENSUEL { get; set; }

    public Nullable<int> KM_DEPART { get; set; }

    public Nullable<int> KM_MAXI { get; set; }

    public Nullable<int> KM_ANNUEL { get; set; }

    public Nullable<System.DateTime> ARRET_CONTRAT { get; set; }

    public string ENSEMBLE_AVEC { get; set; }

    public string TYPE_CHASSIS_VDS { get; set; }

    public string NUMERO_CHASSIS { get; set; }

    public string MARQUE { get; set; }

    public string NUMERO_CONTRAT { get; set; }

    public string NUMERO_VDS { get; set; }

    public string VARIANTE_CHASSIS { get; set; }

    public string MOTEUR { get; set; }

    public string BOITE_VITESSE { get; set; }

    public string PONT_AR { get; set; }

    public string COMBI { get; set; }

    public Nullable<int> TYPE_CONTRAT { get; set; }

    public string PNEUS { get; set; }

    public string FRIGO { get; set; }

    public string CARROSSERIE { get; set; }

    public string MINES { get; set; }

    public string GRUE { get; set; }

    public string HAYON { get; set; }

    public string VEHI_REMPL { get; set; }

    public string TACHY { get; set; }

    public string TYPE_VEH { get; set; }

    public string TYPE_PROD { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

}

}
