
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QReports
{

using System;
    using System.Collections.Generic;
    
public partial class T_USER
{

    public int CLE_USER { get; set; }

    public string NOM_USER { get; set; }

    public string MOT_DE_PASS { get; set; }

    public Nullable<int> CLE_PROFILE { get; set; }

    public string PRENOM_USER { get; set; }

    public Nullable<int> CLE_INTERV { get; set; }

    public Nullable<int> CLE_DEM { get; set; }

    public Nullable<int> CLE_FOURN { get; set; }

    public Nullable<System.DateTime> DATE_PREC { get; set; }

    public Nullable<System.DateTime> DATE_PROCH { get; set; }

    public Nullable<int> CLE_DECL { get; set; }

    public string SIGNATURE { get; set; }

    public Nullable<int> CLE_MAG_DEF { get; set; }

    public string VOIR_TRAVX_SSI_USER_IN_LIGNES { get; set; }

    public string USER_MM_CS { get; set; }

    public string USER_DI_CS { get; set; }

    public string USER_WEB { get; set; }

    public Nullable<int> CLE_ETAT { get; set; }

    public Nullable<System.DateTime> DATE_VALIDITE { get; set; }

    public Nullable<int> CLE_RESPONSABLE { get; set; }

    public Nullable<System.DateTime> D_CREAT_ENREG { get; set; }

    public Nullable<System.DateTime> D_DERMODIF_ENREG { get; set; }

    public Nullable<int> USER_DERMODIF { get; set; }

    public Nullable<int> SYS_ID { get; set; }

    public Nullable<int> CLE_ARBO_DEFAUT { get; set; }

    public Nullable<int> CLE_LANGUE { get; set; }

    public string AUDROS_LOGIN { get; set; }

    public Nullable<int> CLE_AUDROS_PROFIL { get; set; }

    public string AUDROS_CONFIGURE { get; set; }

    public string LOGIN_USER { get; set; }

    public Nullable<int> CLE_CLIENT { get; set; }

    public Nullable<int> CLE_SITE { get; set; }

}

}
